# This file created by conda-build 3.0.28
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pixman-0.34.0-on-linux_64, last modified Wed Nov  8 21:05:19 2017
# ------------------------------------------------

package:
    name: pixman
    version: 0.34.0
source:
    sha256: 21b6b249b51c6800dc9553b65106e1e37d0e25df942c90531d4c3997aa20a88e
    url: http://cairographics.org/releases/pixman-0.34.0.tar.gz
build:
    number: '3'
    run_exports:
        - pixman >=0.34.0,<1.0a0
    string: hceecf20_3
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_9
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h60973fd_9
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - pkg-config 0.29.2 hf7364cd_5
    run:
        - libgcc-ng 7.2.0.*
test:
    commands:
        - test -f ${PREFIX}/lib/libpixman-1.a
about:
    description: 'Pixman is a low-level software library for pixel manipulation, providing

        features such as image compositing and trapezoid rasterization.

        '
    dev_url: https://cgit.freedesktop.org/pixman/
    home: http://www.pixman.org/
    license: MIT
    license_file: COPYING
    summary: A low-level software library for pixel manipulation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
