# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/alabaster-feedstock/recipe, last modified Sun Sep 17 15:35:17 2017
# ------------------------------------------------

package:
    name: alabaster
    version: 0.7.10
source:
    fn: alabaster-0.7.10.tar.gz
    sha256: 37cdcb9e9954ed60912ebc1ca12a9d12178c26637abdf124e3cde2341c257fe0
    url: https://pypi.io/packages/source/a/alabaster/alabaster-0.7.10.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h306e16b_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - python -c "import alabaster; print(alabaster.get_path())"
    imports:
        - alabaster
about:
    description: 'Alabaster is a visually clean, responsive, and configurable Sphinx

        theme. It is sidebar-enabled and easy to install/use as a Python

        package. As of Sphinx 1.3, Alabaster is selected as the default

        theme for Sphinx.

        '
    dev_url: https://github.com/bitprophet/alabaster
    doc_url: https://anaconda.org/anaconda/alabaster
    home: http://www.sphinx-doc.org/en/stable/index.html
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Configurable, Python 2+3 compatible Sphinx theme.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - r-jain1
