# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/testpath-feedstock/recipe, last modified Sun Sep 17 15:47:48 2017
# ------------------------------------------------

package:
    name: testpath
    version: 0.3.1
source:
    fn: testpath-0.3.1.tar.gz
    sha256: 0d5337839c788da5900df70f8e01015aec141aa3fe7936cb0d0a2953f7ac7609
    url: https://pypi.io/packages/source/t/testpath/testpath-0.3.1.tar.gz
build:
    number: '0'
    script: pip install --no-deps .
    string: py36h8cadb63_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - testpath
about:
    description: 'Testpath contains functions to check things on the filesystem,

        and tools for mocking system commands and recording calls to those.

        '
    dev_url: https://github.com/jupyter/testpath
    doc_url: https://testpath.readthedocs.io
    home: https://testpath.readthedocs.io
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Testpath is a collection of utilities for Python code working with files
        and commands.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - takluyver
