# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/anaconda-client-1.6.9-python3.6-on-linux_64, last modified Wed Jan 31 17:44:15 2018
# ------------------------------------------------

package:
    name: anaconda-client
    version: 1.6.9
source:
    fn: anaconda-client-1.6.9.tar.gz
    sha256: 57b6b3435a7b6ab3c0feece7e9a948755f55481b2c072d1bf9b9ec56e0e7c5ba
    url: https://github.com/Anaconda-Platform/anaconda-client/archive/1.6.9.tar.gz
build:
    entry_points:
        - anaconda = binstar_client.scripts.cli:main
        - binstar = binstar_client.scripts.cli:main
        - conda-server = binstar_client.scripts.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - clyent >=1.2.0
        - nbformat >=4.4.0
        - python >=3.6,<3.7.0a0
        - python-dateutil >=2.6.1
        - pytz
        - pyyaml >=3.12
        - requests >=2.9.1
        - setuptools
        - six
test:
    commands:
        - anaconda --help
        - binstar --help
        - conda-server --help
    imports:
        - binstar_client
        - binstar_client.commands
        - binstar_client.inspect_package
        - binstar_client.inspect_package.tests
        - binstar_client.mixins
        - binstar_client.scripts
        - binstar_client.tests
        - binstar_client.utils
        - binstar_client.utils.notebook
        - binstar_client.utils.notebook.tests
about:
    home: https://github.com/Anaconda-Platform/anaconda-client
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.md
    summary: Anaconda Cloud command line client library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
