# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/sphinxcontrib-websupport-feedstock/recipe, last modified Sun Sep 17 15:47:21 2017
# ------------------------------------------------

package:
    name: sphinxcontrib-websupport
    version: 1.0.1
source:
    fn: sphinxcontrib-websupport-1.0.1.tar.gz
    sha256: 7a85961326aa3a400cd4ad3c816d70ed6f7c740acd7ce5d78cd0a67825072eb9
    url: https://pypi.io/packages/source/s/sphinxcontrib-websupport/sphinxcontrib-websupport-1.0.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36hb5cb234_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sphinxcontrib 1.0 py36h6d0f590_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sphinxcontrib 1.0 py36h6d0f590_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
        - sphinxcontrib
test:
    imports:
        - sphinxcontrib
about:
    description: 'sphinxcontrib-websupport provides a Python API to easily integrate

        Sphinx documentation into your Web application

        '
    dev_url: https://github.com/sphinx-doc/sphinxcontrib-websupport
    doc_url: http://www.sphinx-doc.org/en/stable/
    home: https://pypi.python.org/pypi/sphinxcontrib-websupport
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Sphinx API for Web Apps
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chohner
