# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pyodbc-4.0.22-python3.6-on-linux_64, last modified Tue Jan 23 22:32:03 2018
# ------------------------------------------------

package:
    name: pyodbc
    version: 4.0.22
source:
    fn: pyodbc-4.0.22.tar.gz
    patches:
        - setup.patch
    sha256: e2d742b42c8b92b10018c51d673fe72d925ab90d4dbaaccd4f209e10e228ba73
    url: https://pypi.io/packages/source/p/pyodbc/pyodbc-4.0.22.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36hf484d3e_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - unixodbc 2.3.4 hc36303a_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - python >=3.6,<3.7.0a0
        - unixodbc 2.3.4.*
test:
    imports:
        - pyodbc
about:
    description: 'pyodbc is a Python DB API 2 module for ODBC. This project provides
        an

        up-to-date, convenient interface to ODBC using native data types like

        datetime and decimal.

        '
    dev_url: https://github.com/mkleehammer/pyodbc
    doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
    doc_url: http://mkleehammer.github.io/pyodbc/
    home: https://github.com/mkleehammer/pyodbc
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: DB API Module for ODBC
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
