# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/itsdangerous-feedstock/recipe, last modified Sun Sep 17 15:40:25 2017
# ------------------------------------------------

package:
    name: itsdangerous
    version: '0.24'
source:
    fn: itsdangerous-0.24.tar.gz
    sha256: cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519
    url: https://pypi.io/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h93cc618_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - itsdangerous
about:
    description: 'Internally itsdangerous uses HMAC and SHA1 for signing data and
        bases the

        implementation on the Django signing module.  It also however supports JSON
        Web

        Signatures (JWS).

        '
    dev_url: https://github.com/pallets/itsdangerous
    doc_source_url: https://github.com/pallets/itsdangerous/blob/master/docs/index.rst
    doc_url: http://pythonhosted.org/itsdangerous
    home: https://github.com/pallets/itsdangerous
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Various helpers to pass trusted data to untrusted environments.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
