# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pyzmq-16.0.3-python3.6-on-linux_64, last modified Wed Nov 22 03:19:12 2017
# ------------------------------------------------

package:
    name: pyzmq
    version: 16.0.3
source:
    fn: pyzmq-16.0.3.tar.gz
    sha256: 8a883824147523c0fe76d247dd58994c1c28ef07f1cc5dde595a4fd1c28f2580
    url: https://pypi.io/packages/source/p/pyzmq/pyzmq-16.0.3.tar.gz
build:
    number: '0'
    string: py36he2533c7_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_14
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hf1c97a4_14
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libsodium 1.0.15 hf101ebd_0
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - pip 9.0.1 py36h6c6f9ce_4
        - pkg-config 0.29.2 hf7364cd_5
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zeromq 4.2.2 hbedb6e5_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libsodium 1.0.15 hf101ebd_0
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - pip 9.0.1 py36h6c6f9ce_4
        - pkg-config 0.29.2 hf7364cd_5
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zeromq 4.2.2 hbedb6e5_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng 7.2.0.*
        - libsodium
        - python >=3.6,<3.7.0a0
        - zeromq 4.2*
test:
    commands:
        - py.test --pyargs zmq.tests.test_socket
    imports:
        - zmq
        - zmq.backend.cython.socket
        - zmq.backend.cython.utils
        - zmq.devices.monitoredqueue
    requires:
        - pytest
about:
    description: 'PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and
        fast

        messaging implementation.

        '
    dev_url: https://github.com/zeromq/pyzmq
    doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
    doc_url: https://pyzmq.readthedocs.org/
    home: https://github.com/zeromq/pyzmq
    license: BSD 3-clause
    license_family: BSD
    summary: Python bindings for zeromq
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - msarahan
        - pelson
