# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/qtpy-feedstock/recipe, last modified Sun Sep 17 15:46:15 2017
# ------------------------------------------------

package:
    name: qtpy
    version: 1.3.1
source:
    fn: qtpy-1.3.1.tar.gz
    sha256: 08af2525d59f9eb639946d5ed7a72b002103c5b7369c0ef0dd70ad2696845313
    url: https://pypi.io/packages/source/q/qtpy/QtPy-1.3.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h3691cc8_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - qtpy
        - qtpy.QtGui
    requires:
        - pyqt
about:
    description: 'QtPy is a small abstraction layer that lets you write applications
        using a

        single api call to either PyQt or PySide.

        '
    dev_url: https://github.com/spyder-ide/qtpy
    doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/QtPy
    home: https://github.com/spyder-ide/qtpy
    license: MIT
    license_file: LICENSE.txt
    summary: Abtraction layer for PyQt5/PyQt4/PySide
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Nodd
        - astrofrog
        - ccordoba12
        - goanpeca
