# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/msgpack-python-0.5.1-python3.6-on-linux_64, last modified Thu Jan 11 21:15:59 2018
# ------------------------------------------------

package:
    name: msgpack-python
    version: 0.5.1
source:
    fn: msgpack-python-0.5.1.tar.gz
    sha256: 69aa1eb0e13be1d3bd495ca937eae66df4431126f5cfd5491dc40370e5644853
    url: https://pypi.io/packages/source/m/msgpack-python/msgpack-python-0.5.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h6bb024c_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - python >=3.6,<3.7.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache 2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
