# This file created by conda-build 3.0.28
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zeromq-4.2.2-on-linux_64, last modified Wed Nov  8 19:14:50 2017
# ------------------------------------------------

package:
    name: zeromq
    version: 4.2.2
source:
    patches:
        - 0001-Add-missing-ZeroMQConfig.cmake.in.patch
    sha256: 5b23f4ca9ef545d5bd3af55d305765e3ee06b986263b31967435d285a3e6df6b
    url: https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz
build:
    number: '2'
    string: hbedb6e5_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_9
        - bzip2 1.0.6 h0376d23_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cmake 3.9.4 h142f0e9_0
        - curl 7.55.1 hcb0b314_2
        - expat 2.2.4 h6ea4f2b_2
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h60973fd_9
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h57110d4_9
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libsodium 1.0.13 h31c71d8_2
        - libssh2 1.8.0 h8c220ad_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libuv 1.14.0 h56b52c2_0
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2m h8cfc7e7_0
        - rhash 1.3.5 hbf7ad62_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libsodium 1.0.13 h31c71d8_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
    run:
        - libgcc-ng 7.2.0.*
        - libsodium
        - libstdcxx-ng 7.2.0.*
test:
    commands:
        - test -f ${PREFIX}/lib/libzmq.a
        - test -f ${PREFIX}/lib/libzmq.so
        - test -f ${PREFIX}/lib/libzmq.so.5
        - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfig.cmake
        - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake
about:
    home: http://zeromq.org
    license: LGPL 3
    summary: A high-performance asynchronous messaging library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - mingwandroid
        - minrk
