# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/heapdict-1.0.0-python_3.6-on-linux_64, last modified Wed Feb  7 18:45:44 2018
# ------------------------------------------------

package:
    name: heapdict
    version: 1.0.0
source:
    fn: heapdict-1.0.0.tar.gz
    sha256: 4c8e581f1651ca78da35820fc80b0d50fc060032517f2c7efd9169e204db3793
    url: https://github.com/DanielStutzbach/heapdict/archive/v1.0.0.tar.gz
build:
    number: '2'
    script: python setup.py install
    string: py36_2
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - heapdict
about:
    description: 'heapdict implements the MutableMapping ABC, meaning it works pretty
        much

        like a regular Python dict. It''s designed to be used as a priority queue.

        '
    dev_url: https://github.com/DanielStutzbach/heapdict
    doc_source_url: https://github.com/DanielStutzbach/heapdict/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/HeapDict
    home: http://stutzbachenterprises.com/
    license: BSD 3-Clause
    license_file: LICENSE
    summary: A heap with decrease-key and increase-key operations
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mrocklin
        - ocefpaf
