# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/path.py-10.5-python3.6-on-linux_64, last modified Tue Nov 28 02:08:01 2017
# ------------------------------------------------

package:
    name: path.py
    version: '10.5'
source:
    fn: path.py-10.5.tar.gz
    sha256: 63a7af08676668fd51750f111affbd38c1a13c61aba15c6665b16681771c79a8
    url: https://pypi.io/packages/source/p/path.py/path.py-10.5.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h55ceabb_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - setuptools_scm 1.15.6 py36h9817af8_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - setuptools_scm 1.15.6 py36h9817af8_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - path
about:
    description: 'path.py implements a path objects as first-class entities, allowing
        common

        operations on files to be invoked on those path objects directly.

        '
    dev_url: https://github.com/jaraco/path.py
    doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
    doc_url: https://pathpy.readthedocs.io/en/latest/
    home: https://github.com/jaraco/path.py
    license: MIT
    summary: A module wrapper for os.path
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
