# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/partd-feedstock/recipe, last modified Sun Sep 17 15:43:31 2017
# ------------------------------------------------

package:
    name: partd
    version: 0.3.8
source:
    fn: partd-0.3.8.tar.gz
    sha256: 67291f1c4827cde3e0148b3be5d69af64b6d6169feb9ba88f0a6cfe77089400f
    url: https://pypi.io/packages/source/p/partd/partd-0.3.8.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h36fd896_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - locket 0.2.0 py36h787c0ad_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - toolz 0.8.2 py36h81f2dff_0
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - locket 0.2.0 py36h787c0ad_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - toolz 0.8.2 py36h81f2dff_0
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - locket
        - python >=3.6,<3.7.0a0
        - toolz
test:
    imports:
        - partd
about:
    description: 'Partd stores key-value pairs. Values are raw bytes. It excels at
        shuffling

        operations.

        '
    dev_url: https://github.com/dask/partd
    doc_source_url: https://github.com/dask/partd/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/partd/
    home: https://github.com/dask/partd
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Data structure for on-disk shuffle operations
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jcrist
        - koverholt
        - mrocklin
