# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/babel-2.5.3-python3.6-on-linux_64, last modified Fri Jan 19 15:34:20 2018
# ------------------------------------------------

package:
    name: babel
    version: 2.5.3
source:
    fn: Babel-2.5.3.tar.gz
    sha256: 8ce4cb6fdd4393edd323227cba3a077bceb2a6ce5201c902c65e730046f41f14
    url: https://pypi.io/packages/source/B/Babel/Babel-2.5.3.tar.gz
build:
    entry_points:
        - pybabel = babel.messages.frontend:main
    number: '0'
    script: python setup.py install
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - pytz 2017.3 py36h63b9c63_0
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
        - pytz
test:
    commands:
        - pybabel --help
    imports:
        - babel
        - babel.localtime
        - babel.messages
about:
    description: 'Babel is an integrated collection of utilities that assist in

        internationalizing and localizing Python applications, with an emphasis

        on web-base applications.

        '
    dev_url: https://github.com/python-babel/babel
    doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
    doc_url: http://babel.pocoo.org/en/latest/#user-documentation
    home: http://babel.pocoo.org/
    license: BSD 3-clause
    license_file: LICENSE
    summary: Utilities to internationalize and localize Python applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
        - nehaljwani
