# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-3.6.4-on-linux_64, last modified Tue Jan 16 17:04:45 2018
# ------------------------------------------------

package:
    name: python
    version: 3.6.4
source:
    -   patches:
            - 0001-Add-Anaconda-Distribution-version-logic.patch
            - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
            - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0004-Win32-distutils-Also-look-for-executable.bat.patch
            - 0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
            - 0006-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0007-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0008-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0009-Support-cross-compiling-byte-code.patch
            - 0010-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0011-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0012-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0013-Win32-Do-not-download-externals.patch
            - 0014-Ignore-_PYTHON_SYSCONFIGDATA_NAME-if-it-does-not-exi.patch
            - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
        sha256: 7dc453e1a93c083388eb1a23a256862407f8234a96dc4fae0fc7682020227486
        url: https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
build:
    ignore_run_exports:
        - bzip2
    no_link:
        - bin/python3.6
    number: '1'
    string: hc3d631a_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - make 4.2.1 h3d8f0fa_0
        - pkg-config 0.29.2 he821fa1_6
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - bzip2 1.0.6 h6d464ef_2
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - ncurses >=6.0,<7.0a0
        - openssl >=1.0.2n,<1.0.3a
        - readline >=7.0,<8.0a0
        - sqlite >=3.20.1,<4.0a0
        - tk >=8.6.7,<8.7.0a0
        - xz >=5.2.3,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu python
            -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - conda inspect linkages -p $PREFIX python
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
