# This file created by conda-build 3.1.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/html5lib-1.0.1-python3.6-on-nwani-linux-64, last modified Sun Dec 10 16:22:25 2017
# ------------------------------------------------

package:
    name: html5lib
    version: 1.0.1
source:
    fn: html5lib-1.0.1.tar.gz
    sha256: 66cb0dcfdbbc4f9c3ba1a63fdb511ffdbd4f513b2b6d81b80cd26ce6b3fb3736
    url: https://pypi.io/packages/source/h/html5lib/html5lib-1.0.1.tar.gz
build:
    number: '0'
    script: pip install --no-deps .
    string: py36h2f9c1c0_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36h6c6f9ce_4
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36h6c6f9ce_4
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
        - six >=1.9
        - webencodings
test:
    imports:
        - html5lib
        - html5lib._trie
        - html5lib.filters
        - html5lib.treeadapters
        - html5lib.treebuilders
        - html5lib.treewalkers
about:
    description: 'html5lib is a pure-python library for parsing HTML. It is designed
        to

        conform to the WHATWG HTML specification, as is implemented by all major

        web browsers.

        '
    dev_url: https://github.com/html5lib/html5lib-python
    doc_source_url: https://github.com/html5lib/html5lib-python/blob/master/doc/index.rst
    doc_url: http://html5lib.readthedocs.org/
    home: https://github.com/html5lib/html5lib-python
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: HTML parser based on the WHATWG HTML specification
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
