# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/flask-cors-feedstock/recipe, last modified Sun Sep 17 15:38:28 2017
# ------------------------------------------------

package:
    name: flask-cors
    version: 3.0.3
source:
    fn: Flask-Cors-3.0.3.tar.gz
    sha256: 62ebc5ad80dc21ca0ea9f57466c2c74e24a62274af890b391790c260eb7b754b
    url: https://pypi.io/packages/source/F/Flask-Cors/Flask-Cors-3.0.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h2d857d3_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - flask >=0.9
        - python >=3.6,<3.7.0a0
        - six
test:
    imports:
        - flask_cors
        - flask_cors.core
        - flask_cors.decorator
        - flask_cors.extension
        - flask_cors.version
about:
    description: 'A Flask extension for handling Cross Origin Resource Sharing (CORS),

        making cross-origin AJAX possible. This package exposes a Flask extension

        which by default enables CORS support on all routes, for all origins and

        methods.

        '
    dev_url: https://github.com/corydolphin/flask-cors
    doc_source_url: https://github.com/corydolphin/flask-cors/blob/master/docs/index.rst
    doc_url: http://flask-cors.corydolphin.com/en/latest/
    home: https://github.com/corydolphin/flask-cors
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A Flask extension adding a decorator for CORS support
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
