# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libtiff-4.0.9-on-linux_64, last modified Wed Nov 22 00:34:30 2017
# ------------------------------------------------

package:
    name: libtiff
    version: 4.0.9
source:
    fn: tiff-4.0.9.tar.gz
    sha256: 6e7bdeec2c310734e734d19aae3a71ebe37a4d842e0e23dbb1b8921c0026cfcd
    url: ftp://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz
build:
    number: '0'
    run_exports:
        - libtiff >=4.0.9,<5.0a0
    string: h28f6b97_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_14
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hf1c97a4_14
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h4bc98f9_14
        - jpeg 9b h024ee3a_2
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - jpeg 9b h024ee3a_2
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - jpeg >=9b,<10a
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
        - xz >=5.2.3,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libtiff.a
        - test -f ${PREFIX}/lib/libtiffxx.a
        - test -f ${PREFIX}/lib/libtiff.so
        - test -f ${PREFIX}/lib/libtiffxx.so
about:
    description: 'This software provides support for the Tag Image File Format (TIFF),
        a

        widely used format for storing image data.

        '
    doc_url: http://www.libtiff.org/document.html
    home: http://www.libtiff.org/
    license: HPND
    license_url: http://www.libtiff.org/misc.html
    summary: Support for the Tag Image File Format (TIFF).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - stuarteberg
