# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/conda-verify-feedstock/recipe, last modified Sun Sep 17 15:37:17 2017
# ------------------------------------------------

package:
    name: conda-verify
    version: 2.0.0
source:
    fn: conda-verify-2.0.0.tar.gz
    sha256: 4a43471982a88f30cca2242b27a1dda957df6cd30d5de863d6734ed144ea5c2b
    url: https://github.com/conda/conda-verify/archive/2.0.0.tar.gz
build:
    entry_points:
        - conda-verify = conda_verify.main:main
    number: '0'
    script: python setup.py install
    string: py36h98955d8_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
        - pyyaml
test:
    commands:
        - conda-verify --help
    imports:
        - conda_verify
about:
    description: 'conda-verify is a tool for (passively) verifying conda recipes and
        conda

        packages.

        '
    dev_url: https://github.com/conda/conda-verify
    home: https://github.com/conda/conda-verify
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: tool for validating conda recipes and conda packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
