# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/patchelf-feedstock/recipe, last modified Sun Sep 17 15:43:36 2017
# ------------------------------------------------

package:
    name: patchelf
    version: '0.9'
source:
    fn: patchelf-0.9.tar.gz
    sha256: b0a96997382ec3597aee1376a9f6dfed04053c83f2b3d1062cc7b7cec4c6c95b
    url: http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
build:
    number: '2'
    string: hf79760b_2
requirements:
    build:
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - gcc_linux-64 7.2.0 hc7b1ceb_1
        - gxx_linux-64 7.2.0 h8cc0f3c_1
        - libstdcxx-ng 7.2.0 h24385c6_1
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
test:
    commands:
        - patchelf --help
about:
    description: 'PatchELF is a small utility to modify the dynamic linker and RPATH
        of ELF

        executables.

        '
    dev_url: https://github.com/NixOS/patchelf
    doc_url: http://nixos.org/patchelf.html
    home: http://nixos.org/patchelf.html
    license: GPL 3
    license_file: COPYING
    summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mjuric
