# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cloudpickle-0.5.2-python3.6-on-linux_64, last modified Thu Feb  1 18:25:51 2018
# ------------------------------------------------

package:
    name: cloudpickle
    version: 0.5.2
source:
    fn: cloudpickle-0.5.2.tar.gz
    sha256: b0e63dd89ed5285171a570186751bc9b84493675e99e12789e9a5dc5490ef554
    url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-0.5.2.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_1
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - cloudpickle
about:
    description: 'cloudpickle is extended pickling support for Python objects.

        cloudpickle makes it possible to serialize Python constructs not

        supported by the default pickle module from the Python standard library.

        '
    dev_url: https://github.com/cloudpipe/cloudpickle
    doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/cloudpickle/0.4.0
    home: https://github.com/cloudpipe/cloudpickle
    license: BSD 3-Clause
    license_file: LICENSE
    license_url: https://github.com/cloudpipe/cloudpickle/blob/master/LICENSE
    summary: Extended pickling support for Python objects
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mrocklin
        - nehaljwani
        - ogrisel
        - rgbkrk
