# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/fastcache-1.0.2-python_3.6-on-linux_64, last modified Wed Feb  7 19:02:28 2018
# ------------------------------------------------

package:
    name: fastcache
    version: 1.0.2
source:
    fn: fastcache-1.0.2.tar.gz
    sha256: 867005774917f999854ffd303fbe3793c30c2dc9279b78ec315dd4e57e4284e6
    url: https://pypi.io/packages/source/f/fastcache/fastcache-1.0.2.tar.gz
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h14c3975_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - python -c "import fastcache; fastcache.test()"
    imports:
        - fastcache
        - fastcache._lrucache
    requires:
        - pytest
about:
    description: 'fastcache provides speedup of 10-30x over standard library.

        It passes test suite from standard library for lru_cache.

        '
    dev_url: https://github.com/pbrady/fastcache
    doc_source_url: https://github.com/pbrady/fastcache/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/fastcache/1.0.2
    home: https://github.com/pbrady/fastcache
    license: MIT
    license_family: MIT
    license_file: /tmp/build/80754af9/rsync-recipes/fastcache-1.0.2-python_3.6-on-linux_64/LICENSE
    summary: C implementation of Python 3 lru_cache
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
