# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/hdf5-1.10.1-on-linux_64, last modified Thu Nov 16 04:14:21 2017
# ------------------------------------------------

package:
    name: hdf5
    version: 1.10.1
source:
    patches:
        - test_Makefile.in.patch
    sha256: 048a9d149fb99aaa1680a712963f5a78e9c43b588d0e79d55e06760ec377c172
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
build:
    number: '1'
    run_exports:
        - hdf5 >=1.10.1,<1.10.2.0a0
    string: h9caa474_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_12
        - bzip2 1.0.6 h6d464ef_2
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cmake 3.9.4 h142f0e9_0
        - curl 7.55.1 h78862de_4
        - expat 2.2.5 he0dffb1_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hd763dfe_12
        - gfortran_impl_linux-64 7.2.0 hb3c8cce_2
        - gfortran_linux-64 7.2.0 ha0c5ce7_12
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h41d9e3f_12
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libssh2 1.8.0 h8c220ad_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - libuv 1.14.0 h56b52c2_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - rhash 1.3.5 hbf7ad62_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng 7.2.0.*
        - libgfortran-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - command -v h5c++
        - command -v h5cc
        - command -v h5perf_serial
        - command -v h5redeploy
        - command -v h5fc
        - command -v gif2h5
        - command -v h52gif
        - command -v h5copy
        - command -v h5debug
        - command -v h5diff
        - command -v h5dump
        - command -v h5import
        - command -v h5jam
        - command -v h5ls
        - command -v h5mkgrp
        - command -v h5repack
        - command -v h5repart
        - command -v h5stat
        - command -v h5unjam
        - test -f $PREFIX/lib/libhdf5.a
        - test -f $PREFIX/lib/libhdf5.so
        - test -f $PREFIX/lib/libhdf5_cpp.a
        - test -f $PREFIX/lib/libhdf5_cpp.so
        - test -f $PREFIX/lib/libhdf5_hl.a
        - test -f $PREFIX/lib/libhdf5_hl.so
        - test -f $PREFIX/lib/libhdf5_hl_cpp.a
        - test -f $PREFIX/lib/libhdf5_hl_cpp.so
    files:
        - compound_fortran2003.f90
        - h5_cmprss.c
        - h5_cmprss.f90
        - h5tutr_cmprss.cpp
    requires:
        - gcc_linux-64
        - gfortran_linux-64
        - gxx_linux-64
about:
    description: 'HDF5 supports an unlimited variety of datatypes, and is designed
        for

        flexible and efficient I/O and for high volume and complex data.

        '
    dev_url: https://www.hdfgroup.org/HDF5/release/obtain5.html
    doc_url: https://www.hdfgroup.org/HDF5/doc/
    home: http://www.hdfgroup.org/HDF5/
    license: HDF5
    license_family: BSD
    license_file: COPYING
    summary: HDF5 is a data model, library, and file format for storing and managing
        data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog
        - gillins
        - groutr
        - jakirkham
        - marqh
        - msarahan
        - ocefpaf
