# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libssh2-1.8.0-on-linux_64, last modified Fri Jan 19 19:40:22 2018
# ------------------------------------------------

package:
    name: libssh2
    version: 1.8.0
source:
    fn: libssh2-1.8.0.tar.gz
    sha256: 39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4
    url: https://www.libssh2.org/download/libssh2-1.8.0.tar.gz
build:
    number: '4'
    run_exports:
        - libssh2 >=1.8.0,<2.0a0
    string: h9cfc8f7_4
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - cmake-binary 3.9.1 h2f8e2a0_1
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - openssl 1.0.2n hb7f436b_0
    run:
        - libgcc-ng >=7.2.0
        - openssl >=1.0.2n,<1.0.3a
test:
    commands:
        - test -f $PREFIX/include/libssh2.h
        - test -f $PREFIX/include/libssh2_publickey.h
        - test -f $PREFIX/include/libssh2_sftp.h
        - test -f $PREFIX/lib/libssh2.a
        - test -f $PREFIX/lib/libssh2.so
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - shadowwalkersb
