# This file created by conda-build 3.0.15+197.g41d59b5
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/libtool-feedstock/recipe, last modified Sun Nov  5 09:19:42 2017
# ------------------------------------------------

package:
    name: libtool
    version: 2.4.6
source:
    fn: libtool-2.4.6.tar.gz
    patches:
        - 0001-link-as-needed.patch
    sha256: e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3
    url: http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
build:
    number: '3'
    string: h544aabb_3
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_9
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h60973fd_9
        - libstdcxx-ng 7.2.0 h7a57d05_2
    run:
        - libgcc-ng 7.2.0.*
test:
    commands:
        - libtool --help
about:
    description: 'GNU libtool is a generic library support script. Libtool hides the

        complexity of using shared libraries behind a consistent, portable

        interface.

        '
    dev_url: http://git.savannah.gnu.org/cgit/libtool.git
    doc_url: http://www.gnu.org/software/libtool/manual/
    home: http://www.gnu.org/software/libtool/
    license: GPL 3
    summary: The GNU Portable Library Tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
