# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/sortedcontainers-1.5.9-python3.6-on-linux_64, last modified Fri Jan 12 02:02:28 2018
# ------------------------------------------------

package:
    name: sortedcontainers
    version: 1.5.9
source:
    fn: sortedcontainers-1.5.9.tar.gz
    sha256: 844daced0f20d75c02ce53f373d048ea2e401ad8a7b3a4c43b2aa544b569efb3
    url: https://pypi.io/packages/source/s/sortedcontainers/sortedcontainers-1.5.9.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - sortedcontainers
about:
    description: 'SortedContainers is a sorted collections library, written in pure-Python

        and fast as C-extensions.

        '
    dev_url: https://github.com/grantjenks/sorted_containers/
    doc_source_url: https://github.com/grantjenks/sorted_containers/blob/master/docs/index.rst
    doc_url: http://www.grantjenks.com/docs/sortedcontainers/
    home: http://www.grantjenks.com/docs/sortedcontainers/
    license: Apache 2.0
    summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grantjenks
        - msarahan
        - nehaljwani
        - richafrank
