# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pango-1.41.0-on-linux_64, last modified Tue Jan 23 22:00:12 2018
# ------------------------------------------------

package:
    name: pango
    version: 1.41.0
source:
    sha256: 1f76ef95953dc58ee5d6a53e5f1cb6db913f3e0eb489713ee9266695cae580ba
    url: http://ftp.gnome.org/pub/GNOME/sources/pango/1.41/pango-1.41.0.tar.xz
build:
    number: '0'
    run_exports:
        - pango >=1.41.0,<2.0a0
    string: hd475d92_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cairo 1.14.10 hdf128ce_6
        - fontconfig 2.12.4 h88586e7_1
        - freetype 2.8 hab7d2ae_1
        - glib 2.53.6 h5d9569c_2
        - gobject-introspection 1.53.5 py36h0c36277_0
        - graphite2 1.3.10 hf63cedd_1
        - harfbuzz 1.7.4 hc5b324e_0
        - icu 58.2 h9c2bf20_1
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libxcb 1.12 hcd93eb1_4
        - libxml2 2.9.4 h2e8b1d7_6
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pcre 8.41 hc27e229_1
        - perl 5.26.0 hae598fd_0
        - pixman 0.34.0 hceecf20_3
        - pkg-config 0.29.2 h1bed415_7
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - fontconfig >=2.12.4,<3.0a0
        - freetype >=2.8,<2.9.0a0
        - harfbuzz >=1.7.4,<2.0a0
        - libgcc-ng >=7.2.0
        - libpng >=1.6.34,<1.7.0a0
test:
    commands:
        - pango-view --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'Pango is a library for laying out and rendering of text, with an
        emphasis

        on internationalization. Pango can be used anywhere that text layout is

        needed, though most of the work on Pango so far has been done in the

        context of the GTK+ widget toolkit. Pango forms the core of text and font

        handling for GTK+-2.x.

        '
    dev_url: https://github.com/phuang/pango
    doc_url: http://www.pango.org/
    home: http://www.pango.org/
    license: LGPL-2.1
    license_file: COPYING
    summary: Text layout and rendering engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
