# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/entrypoints-feedstock/recipe, last modified Thu Sep 21 01:14:02 2017
# ------------------------------------------------

package:
    name: entrypoints
    version: 0.2.3
source:
    fn: entrypoints-0.2.3.tar.gz
    sha256: d2d587dde06f99545fb13a383d2cd336a8ff1f359c5839ce3a64c917d10c029f
    url: https://pypi.io/packages/source/e/entrypoints/entrypoints-0.2.3.tar.gz
build:
    number: '2'
    script: python setup.py install
    string: py36h1aec115_2
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
about:
    description: 'Entry points are a way for Python packages to advertise objects
        with

        some common interface. The most common examples are console_scripts

        entry points, which define shell commands by identifying a Python

        function to run

        '
    dev_url: https://github.com/takluyver/entrypoints
    doc_source_url: https://github.com/takluyver/entrypoints/tree/master/doc
    doc_url: https://entrypoints.readthedocs.io/en/latest/
    home: https://github.com/takluyver/entrypoints
    license: MIT License
    license_family: MIT
    license_file: LICENSE
    summary: Discover and load entry points from installed packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - minrk
        - ocefpaf
        - pelson
        - takluyver
