# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pyqt-feedstock/recipe, last modified Sun Sep 17 15:45:19 2017
# ------------------------------------------------

package:
    name: pyqt
    version: 5.6.0
source:
    fn: PyQt5_gpl-5.6.tar.gz
    patches:
        - 0001-Make-warnings-non-fatal.patch
    sha1: 8920e4094470ff93f79e257c37c46f5cd0bff7ab
    url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz
build:
    number: '5'
    string: py36h0386399_5
requirements:
    build:
        - alsa-lib-cos6-x86_64 1.1.0 h6d2b67b_0
        - alsa-lib-devel-cos6-x86_64 1.1.0 hd867495_0
        - atk-cos6-x86_64 1.30.0 he7c67e7_0
        - atk-devel-cos6-x86_64 1.30.0 h9bddbf2_0
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cairo-cos6-x86_64 1.8.8 had002bf_0
        - cairo-devel-cos6-x86_64 1.8.8 h8bd0bf0_0
        - dbus 1.10.22 h3b5a359_0
        - expat 2.2.4 hc00ebd1_1
        - fontconfig 2.12.4 h88586e7_1
        - fontconfig-cos6-x86_64 2.8.0 he5a27ec_0
        - fontconfig-devel-cos6-x86_64 2.8.0 hdc0f659_0
        - freetype 2.8 h52ed37b_0
        - freetype-cos6-x86_64 2.3.11 hda26ef6_0
        - freetype-devel-cos6-x86_64 2.3.11 h781713c_0
        - gcc_linux-64 7.2.0 hc7b1ceb_1
        - gdk-pixbuf2-cos6-x86_64 2.24.1 h9eee21e_0
        - gdk-pixbuf2-devel-cos6-x86_64 2.24.1 haf2bbbe_0
        - glib 2.53.6 hc861d11_1
        - glib2-cos6-x86_64 2.28.8 h1a821f5_0
        - glib2-devel-cos6-x86_64 2.28.8 hda010f4_0
        - gst-plugins-base 1.12.2 he3457e5_0
        - gstreamer 1.12.2 h4f93127_0
        - gtk2-cos6-x86_64 2.24.23 h08a0018_0
        - gtk2-devel-cos6-x86_64 2.24.23 h22b3bcd_0
        - gtkmm24-cos6-x86_64 2.18.2 h76adaa3_0
        - gtkmm24-devel-cos6-x86_64 2.18.2 ha7ccc1c_0
        - gxx_linux-64 7.2.0 h8cc0f3c_1
        - icu 58.2 h211956c_0
        - jpeg 9b habf39ab_1
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libdrm-devel-cos6-x86_64 2.4.65 h5701c1a_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libpng 1.6.32 hda9c8bc_2
        - libselinux-cos6-x86_64 2.0.94 hc7b3062_0
        - libselinux-devel-cos6-x86_64 2.0.94 h87dd427_0
        - libsepol-cos6-x86_64 2.0.41 h6e2433f_0
        - libsepol-devel-cos6-x86_64 2.0.41 h5bbff73_0
        - libstdcxx-ng 7.2.0 h24385c6_1
        - libthai-cos6-x86_64 0.1.12 hf1f4b97_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxcb 1.12 he6ee5dd_2
        - libxcomposite-cos6-x86_64 0.4.3 h496ddd6_0
        - libxcomposite-devel-cos6-x86_64 0.4.3 h7370af7_0
        - libxcursor-cos6-x86_64 1.1.14 h4710796_0
        - libxcursor-devel-cos6-x86_64 1.1.14 h84fcfe3_0
        - libxdamage-cos6-x86_64 1.1.3 h8e310ee_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxfixes-cos6-x86_64 5.0.3 h3a64028_0
        - libxi-cos6-x86_64 1.7.8 h5354da0_0
        - libxi-devel-cos6-x86_64 1.7.8 hda042b6_0
        - libxml2 2.9.4 h6b072ca_5
        - libxrandr-cos6-x86_64 1.5.1 h9e6466e_0
        - libxrandr-devel-cos6-x86_64 1.5.1 h5fb6d88_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - libxscrnsaver-cos6-x86_64 1.2.2 h54af3ee_0
        - libxscrnsaver-devel-cos6-x86_64 1.2.2 h6740434_0
        - libxtst-cos6-x86_64 1.2.3 hefb1821_0
        - libxtst-devel-cos6-x86_64 1.2.3 heca503c_0
        - libxxf86vm-cos6-x86_64 1.1.3 h3cd9653_0
        - mesa-dri-drivers-cos6-x86_64 11.0.7 h6ae8bd2_0
        - mesa-dri1-drivers-cos6-x86_64 7.11 hd08e721_0
        - mesa-libegl-cos6-x86_64 11.0.7 hb6c5e57_0
        - mesa-libegl-devel-cos6-x86_64 11.0.7 h2b7a4b1_0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
        - mesa-libgl-devel-cos6-x86_64 11.0.7 h5a2c0ac_0
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pango-cos6-x86_64 1.28.1 h53c42d8_0
        - pango-devel-cos6-x86_64 1.28.1 hf23b437_0
        - pciutils-devel-cos6-x86_64 3.1.10 h99ed674_0
        - pciutils-libs-cos6-x86_64 3.1.10 hb902eda_0
        - pcre 8.41 hc71a17e_0
        - pixman-cos6-x86_64 0.32.8 h7062e45_0
        - pixman-devel-cos6-x86_64 0.32.8 h92a7580_0
        - pkg-config 0.29.2 h4878432_4
        - pkgconfig-cos6-x86_64 0.23 h07b4811_0
        - python 3.6.2 ha783207_11
        - qt 5.6.2 h974d657_12
        - readline 7.0 hac23ff0_3
        - sip 4.18.1 py36h51ed4ed_2
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - dbus >=1.10.22,<2.0a0
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - python >=3.6,<3.7.0a0
        - qt 5.6.*
        - sip 4.18.*
test:
    commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'
        - conda inspect linkages -p $PREFIX pyqt
    files:
        - pyqt_test.py
    imports:
        - PyQt5.QtCore
        - PyQt5.QtWebKitWidgets
about:
    description: '"PyQt is a set of Python v2 and v3 bindings for The Qt Company''s
        Qt

        application framework and runs on all platforms supported by Qt including

        Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and

        will build against Qt v5. The bindings are implemented as a set of Python

        modules and contain over 1,000 classes."

        '
    dev_url: https://github.com/pyqt
    doc_url: https://www.riverbankcomputing.com/software/pyqt/
    home: http://www.riverbankcomputing.co.uk/software/pyqt
    license: Commercial, GPL-2.0, GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: Python binding of the cross-platform GUI toolkit Qt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - gillins
        - mingwandroid
        - msarahan
        - ocefpaf
