# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/matplotlib-2.1.2-python3.6-on-linux_64, last modified Mon Jan 22 20:22:58 2018
# ------------------------------------------------

package:
    name: matplotlib
    version: 2.1.2
source:
    patches:
        - cfg_qt5agg.patch
    sha256: 613d79282a0a8ba88cfc52dbcf1b08ab070dae395c3d313d141ccc3f87e3c9fa
    url: https://github.com/matplotlib/matplotlib/archive/v2.1.2.tar.gz
build:
    number: '0'
    string: py36h0e671d2_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cycler 0.10.0 py36h93f1223_0
        - dbus 1.10.22 h3b5a359_0
        - expat 2.2.5 he0dffb1_0
        - fontconfig 2.12.4 h88586e7_1
        - freetype 2.8 hab7d2ae_1
        - glib 2.53.6 h5d9569c_2
        - gst-plugins-base 1.12.2 he3457e5_0
        - gstreamer 1.12.2 h4f93127_0
        - icu 58.2 h9c2bf20_1
        - intel-openmp 2018.0.0 hc7b2577_8
        - jpeg 9b h024ee3a_2
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libpng 1.6.32 hbd3595f_4
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libxcb 1.12 hcd93eb1_4
        - libxml2 2.9.4 h2e8b1d7_6
        - mkl 2018.0.1 h19d6760_4
        - ncurses 6.0 h9df7e31_2
        - nose 1.3.7 py36hcdf7029_2
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2n hb7f436b_0
        - pcre 8.41 hc27e229_1
        - pkg-config 0.29.2 h1bed415_7
        - pyparsing 2.2.0 py36hee85983_1
        - pyqt 5.6.0 py36h0386399_5
        - python 3.6.4 hc3d631a_1
        - python-dateutil 2.6.1 py36h88d3b88_1
        - pytz 2017.3 py36h63b9c63_0
        - qt 5.6.2 h974d657_12
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sip 4.18.1 py36h51ed4ed_2
        - six 1.11.0 py36h372c433_1
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - cycler >=0.10
        - freetype >=2.8,<2.9.0a0
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - libpng >=1.6.32,<1.7.0a0
        - libstdcxx-ng >=7.2.0
        - numpy
        - pyparsing
        - pyqt 5.6.*
        - python >=3.6,<3.7.0a0
        - python-dateutil
        - pytz
        - setuptools
        - tk 8.6.*
        - tk >=8.6.7,<8.7.0a0
        - tornado
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - matplotlib
        - matplotlib._cntr
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.backends._tkagg
        - matplotlib.ft2font
        - matplotlib.pyplot
        - matplotlib.ttconv
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
