# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/cycler-feedstock/recipe, last modified Sun Sep 17 15:37:36 2017
# ------------------------------------------------

package:
    name: cycler
    version: 0.10.0
source:
    fn: cycler-v0.10.0.tar.gz
    sha256: b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa
    url: https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h93f1223_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - six 1.10.0 py36hcac75e4_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - six 1.10.0 py36hcac75e4_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
        - six
test:
    imports:
        - cycler
about:
    description: 'Cycler is a package used to create composable style cycles.

        '
    dev_url: https://github.com/matplotlib/cycler
    doc_source_url: https://github.com/matplotlib/cycler/blob/master/doc/source/index.rst
    doc_url: http://matplotlib.org/cycler/
    home: http://matplotlib.org/cycler
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Composable style cycles.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - janschulz
        - ocefpaf
        - pelson
        - tacaswell
