# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/conda-build-3.4.1-python_3.6-on-linux_64, last modified Thu Feb  8 19:30:13 2018
# ------------------------------------------------

package:
    name: conda-build
    version: 3.4.1
source:
    git_rev: 580e54b2f1346df0004808df064013c339c7a3a7
    git_url: https://github.com/conda/conda-build
build:
    entry_points:
        - conda-build = conda_build.cli.main_build:main
        - conda-convert = conda_build.cli.main_convert:main
        - conda-develop = conda_build.cli.main_develop:main
        - conda-index = conda_build.cli.main_index:main
        - conda-inspect = conda_build.cli.main_inspect:main
        - conda-metapackage = conda_build.cli.main_metapackage:main
        - conda-render = conda_build.cli.main_render:main
        - conda-skeleton = conda_build.cli.main_skeleton:main
    number: '0'
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - beautifulsoup4
        - chardet
        - conda  >=4.3
        - conda-verify
        - filelock
        - glob2
        - jinja2
        - patchelf
        - pkginfo
        - python >=3.6,<3.7.0a0
        - pyyaml
        - six
test:
    commands:
        - type -P conda-build
        - conda-build -h
        - type -P conda-convert
        - conda-convert -h
        - type -P conda-develop
        - conda-develop -h
        - type -P conda-index
        - conda-index -h
        - type -P conda-inspect
        - conda-inspect linkages -h \| grep "--name ENVIRONMENT"
        - conda-inspect -h
        - type -P conda-metapackage
        - conda-metapackage -h
        - type -P conda-render
        - conda-render -h
        - type -P conda-skeleton
        - conda-skeleton -h
        - python test_bdist_conda_setup.py bdist_conda --help
    files:
        - test_bdist_conda_setup.py
    imports:
        - conda_build
about:
    description: 'Conda-build contains commands and tools to allow you to build your
        own

        packages for conda.

        '
    dev_url: https://github.com/conda/conda-build
    doc_url: http://conda.pydata.org/docs/
    home: https://github.com/conda/conda-build
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: tools for building conda packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
        - stuertz
