# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/tblib-feedstock/recipe, last modified Sun Sep 17 15:47:43 2017
# ------------------------------------------------

package:
    name: tblib
    version: 1.3.2
source:
    fn: tblib-1.3.2.tar.gz
    sha256: 436e4200e63d92316551179dc540906652878df4ff39b43db30fcf6400444fe7
    url: https://pypi.io/packages/source/t/tblib/tblib-1.3.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h34cf8b6_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - tblib
about:
    description: 'tblib allows you to Pickle tracebacks and raise exceptions with
        pickled

        tracebacks in different processes.This allows better error handling when

        running code over multiple processes.

        '
    dev_url: https://github.com/ionelmc/python-tblib
    doc_source_url: https://github.com/ionelmc/python-tblib/blob/master/docs/index.rst
    doc_url: https://python-tblib.readthedocs.io/en/latest/
    home: https://github.com/ionelmc/python-tblib
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Traceback serialization library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
