# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxml2-2.9.7-on-linux_64, last modified Fri Jan 26 16:36:31 2018
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.7
source:
    sha256: f63c5e7d30362ed28b38bfa1ac6313f9a80230720b7fb6c80575eeab3ff5900c
    url: ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz
build:
    number: '0'
    run_exports:
        - libxml2 >=2.9.7,<2.10.0a0
    string: h26e45fe_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - m4 1.4.18 h4e445db_0
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_7
    host:
        - icu 58.2 h9c2bf20_1
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - xz >=5.2.3,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
        - conda inspect linkages -p $PREFIX libxml2
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
