# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/freetype-2.8-on-linux_64, last modified Fri Nov 10 22:17:56 2017
# ------------------------------------------------

package:
    name: freetype
    version: '2.8'
source:
    fn: freetype-2.8.tar.bz2
    sha256: a3c603ed84c3c2495f9c9331fe6bba3bb0ee65e06ec331e0a0fb52158291b40b
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.8.tar.bz2
build:
    number: '1'
    run_exports:
        - freetype >=2.8,<2.9.0a0
    string: hab7d2ae_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_11
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h4118e58_11
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libpng 1.6.32 hda9c8bc_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - zlib 1.2.11 ha838bed_2
    host:
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libpng 1.6.32 hda9c8bc_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng 7.2.0.*
        - libpng >=1.6.32,<1.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - freetype-config --version
        - conda inspect linkages -p $PREFIX freetype
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0 and FreeType
    license_url: http://freetype.sourceforge.net/FTL.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
