# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/decorator-4.2.1-python3.6-on-linux_64, last modified Fri Jan 19 15:28:16 2018
# ------------------------------------------------

package:
    name: decorator
    version: 4.2.1
source:
    fn: decorator-4.2.1.tar.gz
    sha256: 7d46dd9f3ea1cf5f06ee0e4e1277ae618cf48dfb10ada7c8427cd46c42702a0e
    url: https://pypi.io/packages/source/d/decorator/decorator-4.2.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps .
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36h6c6f9ce_4
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - decorator
about:
    description: 'Preserve the signature of decorated functions in a consistent way

        across Python releases.

        '
    dev_url: https://github.com/micheles/decorator
    doc_source_url: https://github.com/micheles/decorator/tree/master/docs
    doc_url: http://decorator.readthedocs.io/en/stable/
    home: https://github.com/micheles/decorator
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Better living through Python with decorators.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
