# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/h5py-2.7.1-python3.6hdf51.10-on-linux_64, last modified Wed Nov 22 01:19:07 2017
# ------------------------------------------------

package:
    name: h5py
    version: 2.7.1
source:
    fn: h5py-2.7.1.tar.gz
    sha256: 55bdefda47c49973ec24384097d18eb5f84797c057aaf0bf0b6b0f7860ad43e7
    url: https://github.com/h5py/h5py/archive/2.7.1.tar.gz
build:
    number: '0'
    string: py36h3585f63_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_14
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cython 0.26.1 py36h21c49d0_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hf1c97a4_14
        - hdf5 1.10.1 h9caa474_1
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h9df7e31_2
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2m h26d622b_1
        - pkg-config 0.29.2 hf7364cd_5
        - pkgconfig 1.2.2 py36h08d3f6d_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - six 1.11.0 py36h372c433_1
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cython 0.26.1 py36h21c49d0_0
        - hdf5 1.10.1 h9caa474_1
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h9df7e31_2
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2m h26d622b_1
        - pkg-config 0.29.2 hf7364cd_5
        - pkgconfig 1.2.2 py36h08d3f6d_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - six 1.11.0 py36h372c433_1
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - hdf5
        - hdf5 >=1.10.1,<1.10.2.0a0
        - libgcc-ng 7.2.0.*
        - numpy
        - python >=3.6,<3.7.0a0
        - six
test:
    imports:
        - h5py
about:
    description: 'H5py uses straightforward NumPy and Python metaphors, like dictionary
        and

        NumPy array syntax.

        '
    dev_url: https://github.com/h5py/h5py
    doc_url: http://docs.h5py.org
    home: http://www.h5py.org/
    license: BSD 3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
