# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pillow-5.0.0-python3.6-on-nwani-linux-64, last modified Thu Jan  4 20:20:32 2018
# ------------------------------------------------

package:
    name: pillow
    version: 5.0.0
source:
    sha256: 12f29d6c23424f704c66b5b68c02fe0b571504459605cfe36ab8158359b0e1bb
    url: https://pypi.io/packages/source/P/Pillow/Pillow-5.0.0.tar.gz
build:
    number: '0'
    string: py36h3deb7b8_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - freetype 2.8 hab7d2ae_1
        - jpeg 9b h024ee3a_2
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libpng 1.6.32 hbd3595f_4
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtiff 4.0.9 h28f6b97_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - freetype >=2.8,<2.9.0a0
        - jpeg >=9b,<10a
        - libgcc-ng >=7.2.0
        - libtiff >=4.0.9,<5.0a0
        - olefile
        - python >=3.6,<3.7.0a0
        - tk >=8.6.7,<8.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - PIL
        - PIL.Image
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
        - PIL._imagingtk
about:
    description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

        adds image processing capabilities to your Python interpreter.

        '
    dev_url: https://github.com/python-pillow/Pillow
    doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
    doc_url: http://pillow.readthedocs.io/en/4.2.x/
    home: http://python-imaging.github.io/
    license: PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
        - pelson
