# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/filelock-2.0.13-python3.6-on-linux_64, last modified Tue Nov 21 17:33:29 2017
# ------------------------------------------------

package:
    name: filelock
    version: 2.0.13
source:
    fn: filelock-2.0.13.tar.gz
    sha256: d05079e7d7cae7576e192749d3461999ca6b0843d35b0f79f1fa956b0f6fc7d8
    url: https://pypi.io/packages/source/f/filelock/filelock-2.0.13.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py36h646ffb5_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - filelock
about:
    description: 'A filelock provides a synchronisation mechanism between different

        instances of your application, similar to a thread lock. It can be

        used to signalize that files, directories or other resources are

        currently used or manipulated (Think of a sync.lock file). Only the

        existence of the lockfile is watched for this purpose. The file itself

        can not be written and is always empty.

        '
    dev_url: https://github.com/benediktschmitt/py-filelock
    doc_source_url: https://github.com/benediktschmitt/py-filelock/tree/master/docs
    doc_url: https://filelock.readthedocs.io/en/latest/
    home: https://github.com/benediktschmitt/py-filelock
    license: Public Domain
    license_family: Public-Domain
    license_file: LICENSE.rst
    summary: A platform independent file lock.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mariusvniekerk
