# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/contextlib2-feedstock/recipe, last modified Sun Sep 17 15:37:24 2017
# ------------------------------------------------

package:
    name: contextlib2
    version: 0.5.5
source:
    fn: contextlib2-0.5.5.tar.gz
    sha256: 509f9419ee91cdd00ba34443217d5ca51f5a364a404e1dce9e8979cea969ca48
    url: https://pypi.io/packages/source/c/contextlib2/contextlib2-0.5.5.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h6c84a62_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - contextlib2
about:
    description: 'Contextlib2 provides backports of features in the latest version
        of the

        standard library''s contextlib module to earlier Python versions. It also

        serves as a real world proving ground for potential future enhancements

        to that module.

        '
    dev_url: https://github.com/jazzband/contextlib2
    doc_source_url: https://github.com/jazzband/contextlib2/blob/master/docs/index.rst
    doc_url: http://contextlib2.readthedocs.org
    home: http://contextlib2.readthedocs.org
    license: PSF
    license_family: PSF
    license_file: LICENSE.txt
    summary: Backports and enhancements for the contextlib module
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - jakirkham
