# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/sphinx-1.6.6-python3.6-on-linux_64, last modified Fri Jan 12 02:01:50 2018
# ------------------------------------------------

package:
    name: sphinx
    version: 1.6.6
source:
    fn: Sphinx-1.6.6.tar.gz
    sha256: c39a6fa41bd3ec6fc10064329a664ed3a3ca2e27640a823dc520c682e4433cdb
    url: https://pypi.io/packages/source/S/Sphinx/Sphinx-1.6.6.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - alabaster
        - babel
        - docutils
        - imagesize
        - jinja2
        - pygments
        - python >=3.6,<3.7.0a0
        - requests
        - six
        - snowballstemmer
        - sphinxcontrib-websupport
        - typing
test:
    commands:
        - sphinx-build -h
        - sphinx-quickstart --version
        - sphinx-quickstart -h
        - sphinx-apidoc -h
        - sphinx-autogen -h
    imports:
        - sphinx
        - sphinx.pycode
about:
    description: 'Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation,

        written by Georg Brandl and licensed under the BSD license.

        It was originally created for the new Python documentation, and it has excellent

        facilities for the documentation of Python projects, but C/C++ is already
        supported

        as well, and it is planned to add special support for other languages as well.

        '
    dev_url: https://github.com/sphinx-doc/sphinx
    doc_source_url: https://github.com/sphinx-doc/sphinx/blob/master/doc/contents.rst
    doc_url: http://www.sphinx-doc.org/en/stable/contents.html
    home: http://www.sphinx-doc.org
    license: BSD 2-clause
    license_file: LICENSE
    summary: Sphinx is a tool that makes it easy to create intelligent and beautiful
        documentation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chohner
        - jakirkham
