# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/nbformat-feedstock/recipe, last modified Sun Sep 17 15:42:31 2017
# ------------------------------------------------

package:
    name: nbformat
    version: 4.4.0
source:
    fn: nbformat-4.4.0.tar.gz
    sha256: f7494ef0df60766b7cabe0a3651556345a963b74dbc16bc7c18479041170d402
    url: https://pypi.io/packages/source/n/nbformat/nbformat-4.4.0.tar.gz
build:
    entry_points:
        - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
    number: '0'
    script: pip install --no-deps .
    string: py36h31c9010_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - ipython_genutils
        - jsonschema >=2.4,!=2.5.0
        - jupyter_core
        - python >=3.6,<3.7.0a0
        - traitlets >=4.1
test:
    commands:
        - jupyter-trust -h
    imports:
        - nbformat
about:
    description: 'nbformat contains the reference implementation of the Jupyter Notebook

        format, and Python APIs for working with notebooks.

        '
    dev_url: https://github.com/jupyter/nbformat
    doc_url: http://nbformat.readthedocs.org
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: The reference implementation of the Jupyter Notebook format
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - mpacer
        - ocefpaf
        - pelson
        - takluyver
