# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/snowballstemmer-feedstock/recipe, last modified Sun Sep 17 15:47:09 2017
# ------------------------------------------------

package:
    name: snowballstemmer
    version: 1.2.1
source:
    fn: snowballstemmer-1.2.1.tar.gz
    sha256: 919f26a68b2c17a7634da993d91339e288964f93c274f1343e3bbbe2096e1128
    url: https://pypi.io/packages/source/s/snowballstemmer/snowballstemmer-1.2.1.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py36h6febd40_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - snowballstemmer
about:
    description: 'Snowball is a small string processing language designed for creating

        stemming algorithms for use in Information Retrieval. The Snowball

        compiler translates a Snowball script into another language - currently

        ISO C, Java and Python are supported.

        '
    dev_url: https://github.com/shibukawa/snowball_py
    doc_source_url: https://github.com/shibukawa/snowball_py/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/snowballstemmer
    home: https://github.com/shibukawa/snowball_py
    license: BSD-2-Clause
    license_file: LICENSE.rst
    summary: Snowball stemming library collection for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chohner
