# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/packaging-feedstock/recipe, last modified Sun Sep 17 15:43:17 2017
# ------------------------------------------------

package:
    name: packaging
    version: '16.8'
source:
    fn: packaging-16.8.tar.gz
    sha256: 5d50835fdf0a7edf0b55e311b7c887786504efea1177abd7e69329a8e5ea619e
    url: https://pypi.io/packages/source/p/packaging/packaging-16.8.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36ha668100_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pyparsing 2.2.0 py36hee85983_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - six 1.10.0 py36hcac75e4_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - pyparsing 2.2.0 py36hee85983_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - six 1.10.0 py36hcac75e4_1
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - pyparsing
        - python >=3.6,<3.7.0a0
        - six
test:
    imports:
        - packaging
about:
    dev_url: https://github.com/pypa/packaging
    doc_source_url: https://github.com/pypa/packaging/tree/master/docs
    doc_url: https://packaging.pypa.io/en/latest/
    home: https://github.com/pypa/packaging
    license: Apache 2.0 or BSD 2-Clause
    license_file: LICENSE
    summary: Core utilities for Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - nicoddemus
