# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/numpy-1.14.0-python3.6-on-linux_64, last modified Wed Jan 24 21:36:02 2018
# ------------------------------------------------

package:
    name: numpy
    version: 1.14.0
source:
    git_rev: 6914bb41f0fb3c1ba500bae4e7d671da9536786f
    git_url: https://github.com/numpy/numpy
    patches:
        - 0001-use-mklfft-when-available.patch
        - 0002-simplify-arch-flags.patch
        - 0003-use-gfortran-from-env-variable.patch
        - 0005-intel-init-mkl.patch
build:
    number: '1'
    requires_features:
        blas: mkl
    string: py36h3dfced4_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gfortran_impl_linux-64 7.2.0 hb3c8cce_2
        - gfortran_linux-64 7.2.0 25
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cython 0.27.3 py36h1860423_0
        - intel-openmp 2018.0.0 hc7b2577_8
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.1 h19d6760_4
        - mkl-devel 2018.0.1 h470d631_5
        - mkl-include 2018.0.1 hc7b2577_4
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libgfortran-ng  >=7,<8.0a0
        - mkl
        - python >=3.6,<3.7.0a0
test:
    commands:
        - f2py -h
        - python -c "import numpy; numpy.show_config()"
        - conda inspect linkages -p $PREFIX numpy
    imports:
        - numpy
        - numpy.linalg.lapack_lite
    requires:
        - gcc_linux-64
        - gfortran_linux-64
        - nose
about:
    description: 'NumPy is the fundamental package needed for scientific computing
        with Python.

        '
    dev_source_url: https://github.com/numpy/numpy/tree/master/doc
    dev_url: https://github.com/numpy/numpy
    doc_url: https://docs.scipy.org/doc/numpy-1.14.0/reference/
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
