# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/python-dateutil-feedstock/recipe, last modified Sun Sep 17 15:45:43 2017
# ------------------------------------------------

package:
    name: python-dateutil
    version: 2.6.1
source:
    fn: python-dateutil-2.6.1.tar.gz
    sha256: 891c38b2a02f5bb1be3e4793866c8df49c7d19baabf9c1bad62547e0b4866aca
    url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.6.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h88d3b88_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
        - six
test:
    imports:
        - dateutil
        - dateutil.rrule
about:
    description: 'The dateutil module provides powerful extensions to the standard
        datetime

        module, available in Python.

        '
    dev_url: https://github.com/dateutil/dateutil/
    doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst
    doc_url: https://dateutil.readthedocs.org/en/latest/
    home: https://dateutil.readthedocs.org/
    license: BSD 3-clause
    license_file: LICENSE
    summary: Extensions to the standard Python datetime module.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
