# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/scikit-image-0.13.1-python3.6-on-linux_64, last modified Fri Jan  5 17:58:25 2018
# ------------------------------------------------

package:
    name: scikit-image
    version: 0.13.1
source:
    sha256: 353879ddf7483f4621872c49cd9bc8a0ad1c3154ac0670b70799922f4cb899e8
    url: https://pypi.io/packages/source/s/scikit-image/scikit-image-0.13.1.tar.gz
build:
    entry_points:
        - skivi = skimage.scripts.skivi:main
    number: '1'
    script:
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h14c3975_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - alabaster 0.7.10 py36h306e16b_0
        - asn1crypto 0.23.0 py36h4639342_0
        - babel 2.5.0 py36h7d14adf_0
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cffi 1.11.2 py36h2825082_0
        - chardet 3.0.4 py36h0f667ec_1
        - cryptography 2.1.4 py36hd09be54_0
        - cython 0.27.3 py36h1860423_0
        - docutils 0.14 py36hb0f60f5_0
        - idna 2.6 py36h82fb2a8_1
        - imagesize 0.7.1 py36h52d8127_0
        - intel-openmp 2018.0.0 hc7b2577_8
        - jinja2 2.10 py36ha16c418_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - markupsafe 1.0 py36hd9260cd_1
        - mkl 2018.0.1 h19d6760_4
        - ncurses 6.0 h9df7e31_2
        - numpy 1.9.3 py36h35fcb08_3
        - numpydoc 0.7.0 py36h18f165f_0
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36h6c6f9ce_4
        - pycparser 2.18 py36hf9f622e_1
        - pygments 2.2.0 py36h0d3125c_0
        - pyopenssl 17.5.0 py36h20ba746_0
        - pysocks 1.6.7 py36hd97a5b1_1
        - python 3.6.4 hc3d631a_0
        - pytz 2017.3 py36h63b9c63_0
        - readline 7.0 ha6073c6_4
        - requests 2.18.4 py36he2e5f8d_1
        - scipy 1.0.0 py36hbf646e7_0
        - setuptools 36.5.0 py36he42e2e1_0
        - six 1.11.0 py36h372c433_1
        - snowballstemmer 1.2.1 py36h6febd40_0
        - sphinx 1.6.3 py36he5f0bdb_0
        - sphinxcontrib 1.0 py36h6d0f590_1
        - sphinxcontrib-websupport 1.0.1 py36hb5cb234_1
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - typing 3.6.2 py36h7da032a_0
        - urllib3 1.22 py36hbe7ace6_0
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - dask >=0.5
        - imageio >=2.1.0
        - libgcc-ng >=7.2.0
        - matplotlib >=1.3.1
        - networkx >=1.8
        - numpy  >=1.9.3,<2.0a0
        - pillow >=2.1.0
        - python >=3.6,<3.7.0a0
        - pywavelets >=0.4.0
        - scipy >=0.17
        - six >=1.7.3
test:
    commands:
        - conda inspect linkages -p $PREFIX scikit-image
    imports:
        - skimage
about:
    home: http://scikit-image.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Image processing routines for SciPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Korijn
        - ivoflipse
        - jakirkham
        - jni
        - msarahan
        - ocefpaf
