# This file created by conda-build 3.0.22
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pytables-3.4.2-python3.6hdf51.10-on-linux_64, last modified Thu Sep 28 01:02:55 2017
# ------------------------------------------------

package:
    name: pytables
    version: 3.4.2
source:
    fn: PyTables-v3.4.2.tar.gz
    sha256: 629a0227bb2b315c5d97629073696609eaee41d0fc89e03f997412613cd46d3a
    url: https://github.com/PyTables/PyTables/archive/v3.4.2.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '2'
    string: py36h3b5282a_2
requirements:
    build:
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - bzip2 1.0.6 h0376d23_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - gcc_linux-64 7.2.0 hc7b1ceb_1
        - gxx_linux-64 7.2.0 h8cc0f3c_1
        - hdf5 1.10.1 hb0523eb_0
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libgfortran-ng 7.2.0 h6fcbd8e_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - lzo 2.10 h1bfc0ba_1
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numexpr 2.6.2 py36hdd3393f_1
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 h02fb82a_12
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - bzip2 1.0.6 h0376d23_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - hdf5 1.10.1 hb0523eb_0
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libgfortran-ng 7.2.0 h6fcbd8e_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - lzo 2.10 h1bfc0ba_1
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numexpr 2.6.2 py36hdd3393f_1
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 h02fb82a_12
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - bzip2 >=1.0.6,<2.0a0
        - hdf5 >=1.10.1,<1.10.2.0a0
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - lzo >=2.10,<3.0a0
        - numexpr
        - numpy  >=1.9.3,<2.0a0
        - python >=3.6,<3.7.0a0
        - six
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
        - conda inspect linkages -p $PREFIX pytables
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
