# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pytz-2017.3-python3.6-on-linux_64, last modified Tue Nov 21 17:42:34 2017
# ------------------------------------------------

package:
    name: pytz
    version: '2017.3'
source:
    fn: pytz-2017.3.zip
    sha256: fae4cffc040921b8a2d60c6cf0b5d662c1190fe54d718271db4eb17d44a185b7
    url: https://pypi.io/packages/source/p/pytz/pytz-2017.3.zip
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h63b9c63_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - pytz
about:
    description: 'pytz brings the Olson tz database into Python. This library allows

        accurate and cross platform timezone calculations using Python 2.4 or

        higher. It also solves the issue of ambiguous times at the end of daylight

        saving time.

        '
    dev_url: https://github.com/newvem/pytz
    doc_source_url: https://github.com/newvem/pytz/blob/master/README.txt
    doc_url: http://pythonhosted.org/pytz/
    home: http://pythonhosted.org/pytz/
    license: MIT
    license_file: LICENSE.txt
    summary: World timezone definitions, modern and historical.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
