# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/harfbuzz-1.7.4-python2.7-on-linux_64, last modified Tue Jan 23 20:23:03 2018
# ------------------------------------------------

package:
    name: harfbuzz
    version: 1.7.4
source:
    fn: harfbuzz-1.7.4.tar.bz2
    sha256: b5d6ac8415f97f3540d73f3f91c41c5c10f8a4d76350f11a7184062aae88ac0b
    url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.7.4.tar.bz2
build:
    number: '0'
    run_exports:
        - harfbuzz >=1.7.4,<2.0a0
    string: hc5b324e_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - ca-certificates 2017.08.26 h1d4fec5_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - glib 2.53.6 h5d9569c_2
        - gobject-introspection 1.53.5 py27h26494a4_0
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - m4 1.4.18 h4e445db_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pcre 8.41 hc27e229_1
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_7
        - python 2.7.14 h1571d57_29
        - readline 7.0 ha6073c6_4
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - zlib 1.2.11 ha838bed_2
    host:
        - cairo 1.14.10 hdf128ce_6
        - fontconfig 2.12.4 h88586e7_1
        - freetype 2.8 hab7d2ae_1
        - glib 2.53.6 h5d9569c_2
        - graphite2 1.3.10 hf63cedd_1
        - icu 58.2 h9c2bf20_1
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libpng 1.6.32 hbd3595f_4
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libxcb 1.12 hcd93eb1_4
        - libxml2 2.9.4 h2e8b1d7_6
        - pcre 8.41 hc27e229_1
        - pixman 0.34.0 hceecf20_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - cairo >=1.14.10,<2.0a0
        - freetype >=2.8,<2.9.0a0
        - glib >=2.53.6,<2.54.0a0
        - graphite2 >=1.3.10,<2.0a0
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - libxcb >=1.12,<2.0a0
test:
    commands:
        - test -f $PREFIX/lib/libharfbuzz-icu.so
        - test -f $PREFIX/lib/libharfbuzz.so
        - test -f $PREFIX/include/harfbuzz/hb-ft.h
        - hb-view --version
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'HarfBuzz is a text shaping library. New Harbuzz targets various
        font

        technologies while Old HarfBuzz targets only OpenType fonts.

        '
    dev_url: https://github.com/behdad/harfbuzz
    doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
    home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
    license: MIT
    license_file: COPYING
    summary: An OpenType text shaping engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
