# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter_client-5.2.2-python3.6-on-linux_64, last modified Thu Jan 25 19:51:37 2018
# ------------------------------------------------

package:
    name: jupyter_client
    version: 5.2.2
source:
    fn: jupyter_client-5.2.2.tar.gz
    sha256: 83d5e23132f0d8f79ccd3939f53fb9fa97f88a896a85114dc48d0e86909b06c4
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-5.2.2.tar.gz
build:
    entry_points:
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    number: '0'
    script: pip install --no-deps .
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36h6c6f9ce_4
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - jupyter_core
        - python >=3.6,<3.7.0a0
        - python-dateutil >=2.1
        - pyzmq >=13
        - tornado
        - traitlets
test:
    commands:
        - jupyter kernelspec list
        - jupyter run -h
    imports:
        - jupyter_client
about:
    description: 'jupyter client contains the reference implementation of the Jupyter

        protocol.It also provides Python API for starting, managing and

        communicating with Jupyter kernels.

        '
    dev_url: https://github.com/jupyter/jupyter_client
    doc_source_url: https://github.com/jupyter/jupyter_client/blob/master/docs/index.rst
    doc_url: http://jupyter-client.readthedocs.org/
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: Jupyter protocol implementation and client libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
