# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/imageio-feedstock/recipe, last modified Sun Sep 17 15:39:57 2017
# ------------------------------------------------

package:
    name: imageio
    version: 2.2.0
source:
    fn: imageio-2.2.0.tar.gz
    sha256: 6dd95300d3d64713a2649334390fd9cf96712013172afd6e73b008e00934a73f
    url: https://pypi.io/packages/source/i/imageio/imageio-2.2.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py36he555465_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - numpy
        - pillow
        - python >=3.6,<3.7.0a0
test:
    imports:
        - imageio
about:
    dev_url: https://github.com/imageio/imageio
    doc_url: http://imageio.readthedocs.io
    home: http://imageio.github.io
    license: BSD 2-Clause
    license_file: LICENSE
    summary: a Python library for reading and writing image data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - blink1073
        - jni
