# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/datashape-feedstock/recipe, last modified Sun Sep 17 15:37:48 2017
# ------------------------------------------------

package:
    name: datashape
    version: 0.5.4
source:
    fn: datashape-0.5.4.tar.gz
    sha256: c266c5803dde48b9fa8d8ee51b5b5979ef77443060e32db2d225b72648c638a5
    url: https://github.com/blaze/datashape/archive/0.5.4.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h3ad6b5c_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - multipledispatch >=0.4.7
        - numpy >=1.7
        - python >=3.6,<3.7.0a0
        - python-dateutil
test:
    commands:
        - py.test -vx --doctest-modules --pyargs datashape
    imports:
        - datashape
        - datashape.tests
        - datashape.util
    requires:
        - mock
        - pytest
about:
    description: 'Datashape is a data layout language for array programming.

        It is designed to describe in-situ structured data without requiring

        transformation into a canonical form.

        '
    dev_url: https://github.com/blaze/datashape
    doc_source_url: https://github.com/blaze/datashape/blob/master/docs/source/index.rst
    doc_url: http://datashape.readthedocs.org/en/latest
    home: http://datashape.pydata.org
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A data description language.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
