# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mpfr-3.1.5-on-linux_64, last modified Tue Nov 21 19:20:04 2017
# ------------------------------------------------

package:
    name: mpfr
    version: 3.1.5
source:
    fn: mpfr-3.1.5.tar.bz2
    sha256: f4eb5070883aee3fd8b927751ea63ff95aebe24418cde852439ce74c3dd2513c
    url: http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.5.tar.gz
build:
    number: '2'
    string: h11a74b3_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_14
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 hf1c97a4_14
        - gmp 6.1.2 h6c8ec71_1
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - m4 1.4.18 h4e445db_0
    host:
        - gmp 6.1.2 h6c8ec71_1
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
    run:
        - gmp
        - gmp >=6.1.2
        - libgcc-ng 7.2.0.*
test:
    commands:
        - test -f ${PREFIX}/lib/libmpfr.a
        - test -f ${PREFIX}/lib/libmpfr.so
    requires:
        - gcc_linux-64
about:
    home: http://www.mpfr.org/
    license: LGPL 3
    license_file: /tmp/build/80754af9/mpfr_1511294132932/work/COPYING.LESSER
    summary: The MPFR library is a C library for multiple-precision floating-point
        computations with correct rounding.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
