# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxslt-1.1.32-on-linux_64, last modified Fri Jan 26 16:52:35 2018
# ------------------------------------------------

package:
    name: libxslt
    version: 1.1.32
source:
    fn: libxslt-1.1.32.tar.gz
    sha256: 526ecd0abaf4a7789041622c3950c0e7f2c4c8835471515fd77eec684a355460
    url: ftp://xmlsoft.org/libxml2/libxslt-1.1.32.tar.gz
build:
    number: '0'
    run_exports:
        - libxslt >=1.1.32,<2.0a0
    string: h1312cb7_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - m4 1.4.18 h4e445db_0
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_7
    host:
        - icu 58.2 h9c2bf20_1
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libxml2 2.9.7 h26e45fe_0
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - libxml2 >=2.9.7,<2.10.0a0
test:
    commands:
        - xsltproc --version
        - conda inspect linkages -p $PREFIX libxslt
about:
    description: '"Libxslt is the XSLT C library developed for the GNOME project.

        XSLT itself is a an XML language to define transformation for XML.

        Libxslt is based on libxml2 the XML C library developed for the GNOME project.

        It also implements most of the EXSLT set of processor-portable extensions
        functions

        and some of Saxon''s evaluate and expressions extensions."

        '
    doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc
    doc_url: http://xmlsoft.org/XSLT/
    home: http://xmlsoft.org/XSLT/
    license: MIT
    license_file: COPYING
    summary: The XSLT C library developed for the GNOME project
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
