# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/bkcharts-feedstock/recipe, last modified Sun Sep 17 15:36:07 2017
# ------------------------------------------------

package:
    name: bkcharts
    version: '0.2'
source:
    fn: bkcharts-0.2.tar.gz
    sha256: a5eaa8e78853dcecaa46345812e4fabe9cd3b96330ebf0809f640a4a0556d72e
    url: https://pypi.io/packages/source/b/bkcharts/bkcharts-0.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h735825a_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - numpy >=1.7.1
        - pandas
        - python >=3.6,<3.7.0a0
        - six >=1.5.2
about:
    dev_url: http://github.com/bokeh/bkcharts
    home: http://github.com/bokeh/bkcharts
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: High level chart types built on top of Bokeh
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
