# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pkginfo-feedstock/recipe, last modified Sun Sep 17 15:44:19 2017
# ------------------------------------------------

package:
    name: pkginfo
    version: 1.4.1
source:
    fn: pkginfo-1.4.1.tar.gz
    sha256: bb1a6aeabfc898f5df124e7e00303a5b3ec9a489535f346bfbddb081af93f89e
    url: https://pypi.io/packages/source/p/pkginfo/pkginfo-1.4.1.tar.gz
build:
    entry_points:
        - pkginfo = pkginfo.commandline:main
    number: '1'
    script: python setup.py install  --single-version-externally-managed --record=record.txt
    string: py36h215d178_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - pkginfo --help
    imports:
        - pkginfo
        - pkginfo.tests
about:
    description: 'This package provides an API for querying the distutils metadata
        written in

        the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or

        a binary distribution (e.g., created by running ``bdist_egg``)

        '
    dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk
    doc_url: http://pythonhosted.org/pkginfo/
    home: https://code.launchpad.net/~tseaver/pkginfo/trunk
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Query metadatdata from sdists / bdists / installed packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - janschulz
        - mingwandroid
