# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cytoolz-0.9.0-python3.6-on-linux_64, last modified Fri Jan 12 21:35:45 2018
# ------------------------------------------------

package:
    name: cytoolz
    version: 0.9.0
source:
    sha256: 5ebb55855a8bb7800afa58e52408763935527e0305f35600c71b43c86013dec2
    url: https://pypi.io/packages/source/c/cytoolz/cytoolz-0.9.0.tar.gz
build:
    number: '0'
    script: python setup.py install --no-cython --single-version-externally-managed
        --record=record.txt
    string: py36h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - toolz 0.9.0 py36_0
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
        - toolz >=0.8.0
test:
    commands:
        - nosetests --with-doctest cytoolz
    imports:
        - cytoolz
        - cytoolz.curried
    requires:
        - nose
        - toolz 0.8.2.*
about:
    description: 'CyToolz is the Cython implementation of the toolz package, which
        provides

        high performance utility functions for iterables, functions, and

        dictionaries.

        '
    dev_url: https://github.com/pytoolz/cytoolz
    doc_source_url: https://github.com/pytoolz/cytoolz/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/cytoolz
    home: https://github.com/pytoolz/cytoolz
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Cython implementation of Toolz. High performance functional utilities.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - eriknw
        - jakirkham
        - jcrist
        - mrocklin
