# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/backports.shutil_get_terminal_size-feedstock/recipe, last modified Thu Sep 21 01:13:55 2017
# ------------------------------------------------

package:
    name: backports.shutil_get_terminal_size
    version: 1.0.0
source:
    fn: backports.shutil_get_terminal_size-1.0.0.tar.gz
    sha256: 713e7a8228ae80341c70586d1cc0a8caa5207346927e23d09dcbcaf18eadec80
    url: https://pypi.io/packages/source/b/backports.shutil_get_terminal_size/backports.shutil_get_terminal_size-1.0.0.tar.gz
build:
    number: '2'
    script: pip install --no-deps .
    string: py36hfea85ff_2
requirements:
    build:
        - backports 1.0 py36hfa02d7e_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - backports 1.0 py36hfa02d7e_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - backports
        - python >=3.6,<3.7.0a0
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    license_file: LICENSE
    summary: A backport of the get_terminal_size function from Python 3.3's shutil.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
