# This file created by conda-build 3.3.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/certifi-2018.1.18-python3.6-on-linux_64, last modified Fri Jan 26 15:20:26 2018
# ------------------------------------------------

package:
    name: certifi
    version: 2018.1.18
source:
    fn: certifi-2018.1.18.tar.gz
    sha256: edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d
    url: https://pypi.io/packages/source/c/certifi/certifi-2018.1.18.tar.gz
build:
    number: '0'
    preserve_egg_dir: 'True'
    script: python setup.py install
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - sqlite 3.21.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
