# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/wheel-0.30.0-python3.6-on-linux_64, last modified Tue Nov 21 16:04:54 2017
# ------------------------------------------------

package:
    name: wheel
    version: 0.30.0
source:
    fn: wheel-0.30.0.tar.gz
    sha256: 9515fe0a94e823fd90b08d22de45d7bde57c90edce705b22f5e1ecf7e1b653c8
    url: https://pypi.io/packages/source/w/wheel/wheel-0.30.0.tar.gz
build:
    entry_points:
        - wheel=wheel.tool:main
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36hfd4bba0_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2m h26d622b_1
        - python 3.6.3 h6c0c0dc_5
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
about:
    home: https://bitbucket.org/pypa/wheel/
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
