# This file created by conda-build 3.2.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/send2trash-1.4.2-python3.6-on-linux_64, last modified Fri Jan 19 15:48:07 2018
# ------------------------------------------------

package:
    name: send2trash
    version: 1.4.2
source:
    fn: Send2Trash-1.4.2.tar.gz
    sha256: 725fbce571dffe0b640e2f1788d52c3c544b510f9d8f69b2597c8c2555bc8441
    url: https://pypi.io/packages/source/S/Send2Trash/Send2Trash-1.4.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - echo test > test.txt
        - python -c "from send2trash import *; send2trash('test.txt')"
    imports:
        - send2trash
about:
    home: https://github.com/hsoft/send2trash
    license: BSD-3-Clause
    license_family: BSD
    license_file: /tmp/build/80754af9/rsync-recipes/send2trash-1.4.2-python3.6-on-linux_64/LICENSE
    summary: Python library to natively send files to Trash (or Recycle bin) on all
        platforms.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
