# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/libedit-feedstock/recipe, last modified Sun Sep 17 15:35:06 2017
# ------------------------------------------------

package:
    name: libedit
    version: '3.1'
source:
    patches:
        - 0001-Also-look-in-libtinfo-for-tgetent.patch
    sha256: 91f2d90fbd2a048ff6dad7131d9a39e690fd8a8fd982a353f1333dd4017dd4be
    url: http://thrysoee.dk/editline/libedit-20170329-3.1.tar.gz
build:
    string: heed3624_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - gcc_linux-64 7.2.0 hc7b1ceb_1
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - m4 1.4.18 h4e445db_0
        - ncurses 6.0 h06874d7_1
        - perl 5.26.0 hae598fd_0
    host:
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
    run:
        - libgcc-ng >=7.2.0
        - ncurses 6.0.*
about:
    description: 'This is an autotool- and libtoolized port of the NetBSD Editline
        library

        (libedit). This Berkeley-style licensed command line editor library provides

        generic line editing, history, and tokenization functions, similar to those

        found in GNU Readline

        '
    home: http://thrysoee.dk/editline/
    license: 3-Clause BSD
    license_family: BSD
    license_file: COPYING
    summary: Editline Library (libedit)
extra:
    copy_test_source_files: true
    final: true
