# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pywavelets-feedstock/recipe, last modified Sun Sep 17 15:45:53 2017
# ------------------------------------------------

package:
    name: pywavelets
    version: 0.5.2
source:
    fn: PyWavelets-0.5.2.tar.gz
    sha256: e36d629f40f7781da2dcaa2139bc476e9deaf91d79f675b5ce0bde6e775d1b53
    url: https://github.com/PyWavelets/pywt/archive/v0.5.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36he602eb0_0
requirements:
    build:
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - gcc_linux-64 7.2.0 hc7b1ceb_1
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libgfortran-ng 7.2.0 h6fcbd8e_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numpy 1.9.3 py36h9530901_2
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libgfortran-ng 7.2.0 h6fcbd8e_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numpy 1.9.3 py36h9530901_2
        - openssl 1.0.2l h9d1a558_3
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - libgcc-ng >=7.2.0
        - numpy  >=1.9.3,<2.0a0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX pywavelets
    requires:
        - nose
about:
    home: https://github.com/PyWavelets/pywt
    license: MIT
    license_file: COPYING
    summary: Discrete Wavelet Transforms in Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grlee77
        - jakirkham
        - ocefpaf
