# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pycrypto-2.6.1-python_3.6-on-linux_64, last modified Wed Feb  7 19:04:15 2018
# ------------------------------------------------

package:
    name: pycrypto
    version: 2.6.1
source:
    fn: pycrypto-2.6.1.tar.gz
    md5: 55a61a054aa66812daf5161a0d5d7eda
    patches:
        - pycrypto_PR_199.diff
        - pycrypto_PR_200.diff
        - pycrypto_PR_22.diff
        - pycrypto_PR_46.diff
    url: https://pypi.io/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
build:
    number: '7'
    script:
        - python setup.py install test
    string: py36h14c3975_7
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
test:
    imports:
        - Crypto
        - Crypto.Cipher
        - Crypto.Hash
        - Crypto.Protocol
        - Crypto.PublicKey
        - Crypto.Random
        - Crypto.Random.Fortuna
        - Crypto.Random.OSRNG
        - Crypto.SelfTest
        - Crypto.SelfTest.Cipher
        - Crypto.SelfTest.Hash
        - Crypto.SelfTest.Protocol
        - Crypto.SelfTest.PublicKey
        - Crypto.SelfTest.Random
        - Crypto.SelfTest.Random.Fortuna
        - Crypto.SelfTest.Random.OSRNG
        - Crypto.SelfTest.Signature
        - Crypto.SelfTest.Util
        - Crypto.Signature
        - Crypto.Util
about:
    description: 'pycrpto, the Python Cryptography Toolkit, is a collection of cryptographic

        modules implementing various algorithms and protocols.

        '
    dev_url: https://github.com/dlitz/pycrypto
    doc_source_url: https://github.com/dlitz/pycrypto/tree/master/Doc
    doc_url: https://www.dlitz.net/software/pycrypto/api/current/
    home: http://www.pycrypto.org/
    license: Public Domain
    license_file: COPYRIGHT
    summary: Cryptographic modules for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
