# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mistune-0.8.3-python3.6-on-linux_64, last modified Fri Jan 12 20:46:34 2018
# ------------------------------------------------

package:
    name: mistune
    version: 0.8.3
source:
    fn: mistune-0.8.3.tar.gz
    sha256: bc10c33bfdcaa4e749b779f62f60d6e12f8215c46a292d05e486b869ae306619
    url: https://pypi.io/packages/source/m/mistune/mistune-0.8.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - nosetests
    imports:
        - mistune
    requires:
        - nose
        - python >=3.6,<3.7.0a0
    source_files:
        - tests
about:
    description: 'Inspired by https://github.com/chjj/marked, Mistune is the fastest
        markdown

        parser in pure Python with renderer features. More features include table,

        footnotes, autolink, fenced code etc.

        '
    dev_url: https://github.com/lepture/mistune
    doc_source_url: https://github.com/lepture/mistune/blob/master/README.rst
    doc_url: https://mistune.readthedocs.io/
    home: https://github.com/lepture/mistune
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: The fastest markdown parser in pure Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - ocefpaf
        - pelson
