# This file created by conda-build 3.0.29
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pcre-8.41-on-linux_64, last modified Mon Nov 13 21:36:00 2017
# ------------------------------------------------

package:
    name: pcre
    version: '8.41'
source:
    fn: pcre-8.41.tar.gz
    sha256: 244838e1f1d14f7e2fa7681b857b3a8566b74215f28133f14a8f5e59241b682c
    url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
build:
    number: '1'
    string: hc27e229_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_11
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h4118e58_11
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h5e79354_11
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - libtool 2.4.6 h544aabb_3
        - pkg-config 0.29.2 hf7364cd_5
    run:
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
test:
    commands:
        - pcre-config --version
        - pcregrep --help
        - pcretest --help
        - test -f "${PREFIX}/include/pcre.h"
        - test -f "${PREFIX}/include/pcre_scanner.h"
        - test -f "${PREFIX}/include/pcre_stringpiece.h"
        - test -f "${PREFIX}/include/pcrecpp.h"
        - test -f "${PREFIX}/include/pcrecpparg.h"
        - test -f "${PREFIX}/include/pcreposix.h"
        - test -f "${PREFIX}/lib/libpcre.a"
        - test -f "${PREFIX}/lib/libpcre.so"
        - test -f "${PREFIX}/lib/libpcrecpp.a"
        - test -f "${PREFIX}/lib/libpcrecpp.so"
        - test -f "${PREFIX}/lib/libpcreposix.a"
        - test -f "${PREFIX}/lib/libpcreposix.so"
about:
    description: 'PCRE implement regular expression pattern matching using the same
        syntax and

        semantics as Perl 5. PCRE has its own native API, as well as a set of wrapper

        functions that correspond to the POSIX regular expression API.

        '
    dev_url: http://vcs.pcre.org/pcre2/
    doc_source_url: https://vcs.pcre.org/pcre2/code/trunk/doc/?sortdir=down
    doc_url: http://www.pcre.org/original/doc/html/
    home: http://www.pcre.org/
    license: BSD 3-Clause
    license_family: BSD
    summary: Regular expression pattern matching using the same syntax and semantics
        as Perl 5.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - scopatz
        - sebastian-luna-valero
