# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/spyder-3.2.6-python3.6-on-nwani-linux-64, last modified Tue Jan  9 19:07:51 2018
# ------------------------------------------------

package:
    name: spyder
    version: 3.2.6
source:
    fn: spyder-3.2.6.tar.gz
    patches:
        - zmq.patch
    sha256: 87d6a4f5ee1aac4284461ee3584c3ade50cb53feb3fe35abebfdfb9be18c526a
    url: https://pypi.io/packages/source/s/spyder/spyder-3.2.6.tar.gz
build:
    entry_points:
        - spyder = spyder.app.start:main
    number: '0'
    osx_is_app: 'True'
    string: py36_0
requirements:
    host:
        - alabaster 0.7.10 py36h306e16b_0
        - asn1crypto 0.23.0 py36h4639342_0
        - babel 2.5.0 py36h7d14adf_0
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - cffi 1.11.2 py36h2825082_0
        - chardet 3.0.4 py36h0f667ec_1
        - cryptography 2.1.4 py36hd09be54_0
        - docutils 0.14 py36hb0f60f5_0
        - idna 2.6 py36h82fb2a8_1
        - imagesize 0.7.1 py36h52d8127_0
        - jinja2 2.10 py36ha16c418_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - markupsafe 1.0 py36hd9260cd_1
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pycparser 2.18 py36hf9f622e_1
        - pygments 2.2.0 py36h0d3125c_0
        - pyopenssl 17.5.0 py36h20ba746_0
        - pysocks 1.6.7 py36hd97a5b1_1
        - python 3.6.4 hc3d631a_0
        - pytz 2017.3 py36h63b9c63_0
        - readline 7.0 ha6073c6_4
        - requests 2.18.4 py36he2e5f8d_1
        - setuptools 36.5.0 py36he42e2e1_0
        - six 1.11.0 py36h372c433_1
        - snowballstemmer 1.2.1 py36h6febd40_0
        - sphinx 1.6.3 py36he5f0bdb_0
        - sphinxcontrib 1.0 py36h6d0f590_1
        - sphinxcontrib-websupport 1.0.1 py36hb5cb234_1
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - typing 3.6.2 py36h7da032a_0
        - urllib3 1.22 py36hbe7ace6_0
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - chardet >=2.0
        - cloudpickle
        - jedi >=0.9
        - nbconvert
        - numpydoc
        - pickleshare
        - psutil
        - pycodestyle
        - pyflakes
        - pygments >=2.0
        - pylint
        - pyqt
        - python >=3.6,<3.7.0a0
        - pyzmq
        - qtawesome >=0.4.1
        - qtconsole >=4.2
        - qtpy >=1.2.0
        - rope >=0.9.4
        - sphinx
test:
    commands:
        - USER=test spyder -h
    imports:
        - spyder
app:
    entry: spyder
    icon: logo.png
    summary: Scientific Python Development Environment
    type: desk
about:
    description: 'Spyder is a powerful interactive development environment for the
        Python

        language with advanced editing, interactive testing, debugging and

        introspection features. Additionally, Spyder is a numerical computing

        environment thanks to the support of IPython and popular Python libraries

        such as NumPy, SciPy, or matplotlib.

        '
    dev_url: https://github.com/spyder-ide/spyder
    doc_url: http://pythonhosted.org/spyder/
    home: https://github.com/spyder-ide/spyder
    license: MIT
    license_file: LICENSE
    summary: Scientific PYthon Development EnviRonment
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - goanpeca
