# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/patsy-0.5.0-python3.6-on-linux_64, last modified Thu Jan 11 21:52:41 2018
# ------------------------------------------------

package:
    name: patsy
    version: 0.5.0
source:
    sha256: e05f38d5c38c8d216f0cc2b765b1069b433c92d628b954fb2fee68d13e42883b
    url: https://pypi.io/packages/source/p/patsy/patsy-0.5.0.tar.gz
build:
    number: '0'
    script:
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - numpy >=1.4.0
        - python >=3.6,<3.7.0a0
        - scipy
        - six
test:
    imports:
        - patsy
about:
    description: 'Patsy is a Python library for describing statistical models (especially

        linear models, or models that have a linear component) and building design

        matrices.

        '
    dev_url: https://github.com/pydata/patsy
    doc_source_url: https://github.com/pydata/patsy/blob/master/doc/index.rst
    doc_url: http://patsy.readthedocs.org/en/latest/
    home: https://github.com/pydata/patsy
    license: BSD-2-Clause, PSF2
    license_family: BSD
    license_file: LICENSE.txt
    summary: Describing statistical models in Python using symbolic formulas
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - croth1
