# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/dask-0.16.1-python3.6-on-linux_64, last modified Thu Jan 11 20:48:47 2018
# ------------------------------------------------

package:
    name: dask
    version: 0.16.1
build:
    number: '0'
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - bokeh
        - cloudpickle >=0.2.1
        - dask-core 0.16.1.*
        - distributed >=1.20.0
        - numpy >=1.10
        - pandas >=0.19.0
        - partd >=0.3.8
        - python >=3.6,<3.7.0a0
        - toolz >=0.7.3
test:
    imports:
        - dask
        - dask.array
        - dask.bag
        - dask.bytes
        - dask.dataframe
        - dask.dataframe.tseries
        - dask.delayed
        - dask.diagnostics
        - dask.distributed
        - distributed
about:
    description: 'Dask is a flexible parallel computing library for analytic computing.

        '
    dev_url: https://github.com/dask/dask
    doc_source_url: https://github.com/dask/dask/blob/master/docs/source/index.rst
    doc_url: http://dask.pydata.org
    home: http://dask.pydata.org/en/latest/
    license: BSD 3-Clause
    summary: Parallel Python with task scheduling
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alimanfoo
        - jakirkham
        - jcrist
        - koverholt
        - martindurant
        - mrocklin
        - pitrou
        - tomaugspurger
