# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/jupyter_console-feedstock/recipe, last modified Thu Sep 21 01:14:10 2017
# ------------------------------------------------

package:
    name: jupyter_console
    version: 5.2.0
source:
    fn: jupyter_console-5.2.0.tar.gz
    sha256: 545dedd3aaaa355148093c5609f0229aeb121b4852995c2accfa64fe3e0e55cd
    url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-5.2.0.tar.gz
build:
    entry_points:
        - jupyter-console = jupyter_console.app:main
    number: '1'
    script: python -m pip install --no-deps .
    string: py36he59e554_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h9d1a558_3
        - pip 9.0.1 py36h30f8307_2
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - wheel 0.29.0 py36he7f4e38_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - ipykernel
        - ipython
        - jupyter_client
        - pexpect
        - prompt_toolkit
        - pygments
        - python >=3.6,<3.7.0a0
test:
    commands:
        - jupyter-console -h
    imports:
        - jupyter_console
        - jupyter_console.tests
about:
    description: 'Jupyter console is a terminal frontend for kernels using the Jupyter
        protocol.

        '
    dev_url: https://github.com/jupyter/jupyter_console
    doc_source_url: https://github.com/jupyter/jupyter_console/blob/master/docs/index.rst
    doc_url: http://jupyter-console.readthedocs.org/
    home: http://jupyter.org
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: Jupyter terminal console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
