# This file created by conda-build 3.4.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bitarray-0.8.1-python_3.6-on-linux_64, last modified Wed Feb  7 19:00:45 2018
# ------------------------------------------------

package:
    name: bitarray
    version: 0.8.1
source:
    fn: bitarray-0.8.1.tar.gz
    sha256: 7da501356e48a83c61f479393681c1bc4b94e5a34ace7e08cb29e7dd9290ab18
    url: https://pypi.io/packages/source/b/bitarray/bitarray-0.8.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h14c3975_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.4.0 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
test:
    imports:
        - bitarray
about:
    description: 'Bitarray provides an object type which efficiently represents an
        array of

        booleans. Bitarrays are sequence types that behave very similarly

        to usual lists. All functionality is implemented in C.

        '
    dev_url: https://github.com/ilanschnell/bitarray
    doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
    home: https://github.com/ilanschnell/bitarray
    license: PSF
    license_file: LICENSE
    summary: efficient arrays of booleans -- C extension
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
