# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/multipledispatch-feedstock/recipe, last modified Sun Sep 17 15:42:19 2017
# ------------------------------------------------

package:
    name: multipledispatch
    version: 0.4.9
source:
    fn: multipledispatch-0.4.9.tar.gz
    sha256: bda6abb8188d9abb429bd17ed15bc7433f77f1b05a78cfff761711ed81daa7a2
    url: https://pypi.io/packages/source/m/multipledispatch/multipledispatch-0.4.9.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h41da3fb_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - multipledispatch
about:
    description: 'This implementation of multiple dispatch is efficient, mostly complete,

        performs static analysis to avoid conflicts, and provides optional

        namespace support.

        '
    dev_url: https://github.com/mrocklin/multipledispatch/
    doc_source_url: https://github.com/mrocklin/multipledispatch/blob/master/docs/source/index.rst
    doc_url: https://multiple-dispatch.readthedocs.io
    home: https://github.com/mrocklin/multipledispatch/
    license: BSD 3-Clause
    license_family: BSD
    summary: Multiple dispatch in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
