ctng_binutils: 2.28.1
sqlite: '3'
vc: '14'
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
gst_plugins_base: '1.12'
libnetcdf: '4.4'
libtiff: '4.0'
harfbuzz: '1.5'
python: '3.6'
xz: '5'
ctng_isl: '0.18'
ctng_gdb: 7.12.1
perl: '5.26'
macos_machine: x86_64-apple-darwin13.4.0
ctng_libc: gnu
libdap4: '3.19'
ctng_vendor: conda_cos6
giflib: '5.1'
geos: 3.6.0
mkl: '2018'
fontconfig: '2.12'
VERBOSE_CM: VERBOSE=1
lua: '5'
ctng_ncurses: '6.0'
tk: '8.6'
libxml2: '2.9'
libpng: '1.6'
ctng_kernel: 2.6.32
ctng_mpc: 1.0.3
openblas: 0.2.19
ctng_gmp: 6.1.2
glib: '2.53'
freetype: '2.8'
expat: '2.2'
ctng_gcc: 7.2.0
libkml: '1.3'
macos_min_version: '10.9'
gstreamer: '1.12'
ctng_sample: x86_64-centos6-linux-gnu
boost: '1.64'
ctng_gettext: 0.19.7
ctng_libiconv: '1.14'
scipy: '0.19'
jpeg: '9'
lzo: '2'
ipython: '6.1'
gnu: 2.12.2
target_platform: linux-64
MACOSX_DEPLOYMENT_TARGET: '10.9'
ctng_mpfr: 3.1.5
VERBOSE_AT: V=1
proj4: '4'
r_base: '3.4'
ctng_target_platform: linux-64
hdf4: '4.2'
hdf5: '1.10'
numpy: '1.9'
dbus: '1'
zlib: '1.2'
ctng_cpu_arch: x86_64
ctng_duma: 2.5.15
blas_impl: mkl
zip_keys:
- !!python/tuple [ctng_target_platform, ctng_cpu_arch]
- !!python/tuple [python, ipython]
icu: '58'
ctng_nature: shared
cpu_optimization_target: nocona
bzip2: '1.0'
