# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/setuptools-38.4.0-python3.6-on-linux_64, last modified Fri Jan 12 20:57:51 2018
# ------------------------------------------------

package:
    name: setuptools
    version: 38.4.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - nodownload.patch
    sha256: 6501fc32f505ec5b3ed36ec65ba48f1b975f52cf2ea101c7b73a08583fd12f75
    url: https://pypi.io/packages/source/s/setuptools/setuptools-38.4.0.zip
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - certifi       >=2016.09
        - python >=3.6,<3.7.0a0
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_source_url: https://github.com/pypa/setuptools/tree/master/docs
    dev_url: https://github.com/pypa/setuptools
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
