# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/scikit-learn-0.19.1-python3.6-on-linux_64, last modified Mon Oct 23 12:56:06 2017
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.19.1
source:
    git_rev: b661a9c81930429cba4a56af291ce2bf8c59f8c9
    git_url: https://github.com/scikit-learn/scikit-learn
build:
    number: '0'
    requires_features:
        blas: mkl
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h7aa7ec6_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_7
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h22f992b_7
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h3aab023_7
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - mkl-devel 2018.0.0 hed7f433_4
        - mkl-include 2018.0.0 h15fc484_2
        - ncurses 6.0 h06874d7_1
        - nose 1.3.7 py36hcdf7029_2
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - scipy 0.19.1 py36h9976243_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - mkl-devel 2018.0.0 hed7f433_4
        - mkl-include 2018.0.0 h15fc484_2
        - ncurses 6.0 h06874d7_1
        - nose 1.3.7 py36hcdf7029_2
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - scipy 0.19.1 py36h9976243_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
        - mkl >=2018.0.0
        - numpy  >=1.9.3,<2.0a0
        - python >=3.6,<3.7.0a0
        - scipy
test:
    commands:
        - nosetests sklearn --exe
        - conda inspect linkages -p $PREFIX scikit-learn
    imports:
        - sklearn
    requires:
        - nose
about:
    home: http://scikit-learn.org/
    license: BSD 3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - amueller
        - astaric
        - jakirkham
        - lesteve
        - ocefpaf
        - ogrisel
