# This file created by conda-build 3.0.28
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/glib-2.53.6-python3.6-on-linux_64, last modified Mon Nov  6 18:54:14 2017
# ------------------------------------------------

package:
    name: glib
    version: 2.53.6
source:
    fn: glib-2.53.6.tar.xz
    sha256: e01296a9119c09d2dccb37ad09f5eaa1e0c5570a473d8fed04fc759ace6fb6cc
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.53/glib-2.53.6.tar.xz
build:
    detect_binary_files_with_prefix: 'true'
    number: '2'
    run_exports:
        - glib >=2.53.6,<2.54.0a0
    string: h5d9569c_2
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_9
        - ca-certificates 2017.08.26 h1d4fec5_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h60973fd_9
        - gettext-cos6-x86_64 0.17 h5b04455_0
        - gettext-devel-cos6-x86_64 0.17 h611b9c9_0
        - gettext-libs-cos6-x86_64 0.17 h1747f9e_0
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h57110d4_9
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2m h8cfc7e7_0
        - pcre 8.41 hc71a17e_0
        - pkg-config 0.29.2 hf7364cd_5
        - python 3.6.3 h0ef2715_3
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - pcre 8.41 hc71a17e_0
        - zlib 1.2.11 hfbfcf68_1
    run:
        - libffi >=3.0.0
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
        - pcre
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'GLib provides the core application building blocks for libraries
        and

        applications written in C. It provides the core object system used in

        GNOME, the main loop implementation, and a large set of utility functions

        functions for strings and common data structures.

        '
    dev_url: https://git.gnome.org/browse/glib/
    doc_source_url: https://git.gnome.org/browse/glib/tree/docs
    doc_url: https://developer.gnome.org/glib/unstable/
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pkgw
        - scopatz
