# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/xlsxwriter-1.0.2-python3.6-on-nwani-linux-64, last modified Sat Oct 21 22:57:03 2017
# ------------------------------------------------

package:
    name: xlsxwriter
    version: 1.0.2
source:
    fn: XlsxWriter-1.0.2.tar.gz
    sha256: a26bbbafff88abffce592ffd5dfaa4c9f08dc44ef4afbf45c70d3e270325f856
    url: https://pypi.io/packages/source/X/XlsxWriter/XlsxWriter-1.0.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h3de1aca_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - xlsxwriter
about:
    description: 'XlsxWriter is a Python module that can be used to write text, numbers,
        formulas

        and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.

        '
    dev_url: https://github.com/jmcnamara/XlsxWriter
    doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf
    doc_url: https://xlsxwriter.readthedocs.org/
    home: https://xlsxwriter.readthedocs.io/
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A Python module for creating Excel XLSX files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mcs07
        - nehaljwani
