# This file created by conda-build 3.0.23
# ------------------------------------------------

package:
    name: libstdcxx-ng
    version: 7.2.0
source:
    path: .
build:
    binary_relocation: 'False'
    detect_binary_files_with_prefix: 'False'
    noarch: false
    number: '2'
    string: h7a57d05_2
about:
    home: https://gcc.gnu.org/
    license: GPL3 with runtime exception
    summary: The GNU C++ Runtime Library
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: compilers_linux-64
        path: /home/msarahan/aggregate/ctng-compilers-feedstock/recipe
        version: 7.2.0
