# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pycodestyle-feedstock/recipe, last modified Sun Sep 17 15:44:46 2017
# ------------------------------------------------

package:
    name: pycodestyle
    version: 2.3.1
source:
    fn: pycodestyle-2.3.1.tar.gz
    sha256: 682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766
    url: https://pypi.io/packages/source/p/pycodestyle/pycodestyle-2.3.1.tar.gz
build:
    entry_points:
        - pycodestyle = pycodestyle:_main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36hf609f19_0
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - setuptools 36.2.2 py36hd224944_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - pycodestyle --help
        - pycodestyle --version
about:
    dev_url: https://github.com/PyCQA/pycodestyle
    doc_url: https://pycodestyle.readthedocs.io/
    home: https://pycodestyle.readthedocs.io/
    license: MIT
    license_family: MIT
    summary: Python style guide checker
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
        - pmlandwehr
        - sigmavirus24
